// Generated by CIRCT firtool-1.62.0
module full_subtractor(
  input  [7:0] io_in_a,
               io_in_b,
  output [7:0] io_out_s,
  output       io_out_c
);

  wire [8:0] result = {1'h0, io_in_a} - {1'h0, io_in_b};
  assign io_out_s = result[7:0];
  assign io_out_c = result[8];
endmodule

module full_adder(
  input  [23:0] io_in_a,
                io_in_b,
  output [23:0] io_out_s,
  output        io_out_c
);

  wire [24:0] result = {1'h0, io_in_a} + {1'h0, io_in_b};
  assign io_out_s = result[23:0];
  assign io_out_c = result[24];
endmodule

module LZC_enc2(
  input  [1:0] io_in_r,
  output [1:0] io_out_e
);

  assign io_out_e = io_in_r == 2'h0 ? 2'h2 : {1'h0, io_in_r == 2'h1};
endmodule

module LZC_Merge2(
  input  [1:0] io_in_h,
               io_in_l,
  output [2:0] io_out_m
);

  assign io_out_m =
    {io_in_h[1] & io_in_l[1],
     io_in_h[1] ? ~(io_in_l[1]) : io_in_h[1],
     io_in_h[1] ? io_in_l[0] : io_in_h[0]};
endmodule

module LZC_Merge3(
  input  [2:0] io_in_h,
               io_in_l,
  output [3:0] io_out_m
);

  assign io_out_m =
    {io_in_h[2] & io_in_l[2],
     io_in_h[2] ? ~(io_in_l[2]) : io_in_h[2],
     io_in_h[2] ? io_in_l[1:0] : io_in_h[1:0]};
endmodule

module LZC_Merge4(
  input  [3:0] io_in_h,
               io_in_l,
  output [4:0] io_out_m
);

  assign io_out_m =
    {io_in_h[3] & io_in_l[3],
     io_in_h[3] ? ~(io_in_l[3]) : io_in_h[3],
     io_in_h[3] ? io_in_l[2:0] : io_in_h[2:0]};
endmodule

module LZC_Merge5(
  input  [4:0] io_in_h,
               io_in_l,
  output [5:0] io_out_m
);

  assign io_out_m =
    {io_in_h[4] & io_in_l[4],
     io_in_h[4] ? ~(io_in_l[4]) : io_in_h[4],
     io_in_h[4] ? io_in_l[3:0] : io_in_h[3:0]};
endmodule

module LZC32_2(
  input  [31:0] io_in_d,
  output [5:0]  io_out_c
);

  wire [4:0] _LZC_Merge4_1_io_out_m;
  wire [4:0] _LZC_Merge4_io_out_m;
  wire [3:0] _LZC_Merge3_3_io_out_m;
  wire [3:0] _LZC_Merge3_2_io_out_m;
  wire [3:0] _LZC_Merge3_1_io_out_m;
  wire [3:0] _LZC_Merge3_io_out_m;
  wire [2:0] _LZC_Merge2_7_io_out_m;
  wire [2:0] _LZC_Merge2_6_io_out_m;
  wire [2:0] _LZC_Merge2_5_io_out_m;
  wire [2:0] _LZC_Merge2_4_io_out_m;
  wire [2:0] _LZC_Merge2_3_io_out_m;
  wire [2:0] _LZC_Merge2_2_io_out_m;
  wire [2:0] _LZC_Merge2_1_io_out_m;
  wire [2:0] _LZC_Merge2_io_out_m;
  wire [1:0] _LZC_enc2_15_io_out_e;
  wire [1:0] _LZC_enc2_14_io_out_e;
  wire [1:0] _LZC_enc2_13_io_out_e;
  wire [1:0] _LZC_enc2_12_io_out_e;
  wire [1:0] _LZC_enc2_11_io_out_e;
  wire [1:0] _LZC_enc2_10_io_out_e;
  wire [1:0] _LZC_enc2_9_io_out_e;
  wire [1:0] _LZC_enc2_8_io_out_e;
  wire [1:0] _LZC_enc2_7_io_out_e;
  wire [1:0] _LZC_enc2_6_io_out_e;
  wire [1:0] _LZC_enc2_5_io_out_e;
  wire [1:0] _LZC_enc2_4_io_out_e;
  wire [1:0] _LZC_enc2_3_io_out_e;
  wire [1:0] _LZC_enc2_2_io_out_e;
  wire [1:0] _LZC_enc2_1_io_out_e;
  wire [1:0] _LZC_enc2_io_out_e;
  LZC_enc2 LZC_enc2 (
    .io_in_r  (io_in_d[1:0]),
    .io_out_e (_LZC_enc2_io_out_e)
  );
  LZC_enc2 LZC_enc2_1 (
    .io_in_r  (io_in_d[3:2]),
    .io_out_e (_LZC_enc2_1_io_out_e)
  );
  LZC_enc2 LZC_enc2_2 (
    .io_in_r  (io_in_d[5:4]),
    .io_out_e (_LZC_enc2_2_io_out_e)
  );
  LZC_enc2 LZC_enc2_3 (
    .io_in_r  (io_in_d[7:6]),
    .io_out_e (_LZC_enc2_3_io_out_e)
  );
  LZC_enc2 LZC_enc2_4 (
    .io_in_r  (io_in_d[9:8]),
    .io_out_e (_LZC_enc2_4_io_out_e)
  );
  LZC_enc2 LZC_enc2_5 (
    .io_in_r  (io_in_d[11:10]),
    .io_out_e (_LZC_enc2_5_io_out_e)
  );
  LZC_enc2 LZC_enc2_6 (
    .io_in_r  (io_in_d[13:12]),
    .io_out_e (_LZC_enc2_6_io_out_e)
  );
  LZC_enc2 LZC_enc2_7 (
    .io_in_r  (io_in_d[15:14]),
    .io_out_e (_LZC_enc2_7_io_out_e)
  );
  LZC_enc2 LZC_enc2_8 (
    .io_in_r  (io_in_d[17:16]),
    .io_out_e (_LZC_enc2_8_io_out_e)
  );
  LZC_enc2 LZC_enc2_9 (
    .io_in_r  (io_in_d[19:18]),
    .io_out_e (_LZC_enc2_9_io_out_e)
  );
  LZC_enc2 LZC_enc2_10 (
    .io_in_r  (io_in_d[21:20]),
    .io_out_e (_LZC_enc2_10_io_out_e)
  );
  LZC_enc2 LZC_enc2_11 (
    .io_in_r  (io_in_d[23:22]),
    .io_out_e (_LZC_enc2_11_io_out_e)
  );
  LZC_enc2 LZC_enc2_12 (
    .io_in_r  (io_in_d[25:24]),
    .io_out_e (_LZC_enc2_12_io_out_e)
  );
  LZC_enc2 LZC_enc2_13 (
    .io_in_r  (io_in_d[27:26]),
    .io_out_e (_LZC_enc2_13_io_out_e)
  );
  LZC_enc2 LZC_enc2_14 (
    .io_in_r  (io_in_d[29:28]),
    .io_out_e (_LZC_enc2_14_io_out_e)
  );
  LZC_enc2 LZC_enc2_15 (
    .io_in_r  (io_in_d[31:30]),
    .io_out_e (_LZC_enc2_15_io_out_e)
  );
  LZC_Merge2 LZC_Merge2 (
    .io_in_h  (_LZC_enc2_15_io_out_e),
    .io_in_l  (_LZC_enc2_14_io_out_e),
    .io_out_m (_LZC_Merge2_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_1 (
    .io_in_h  (_LZC_enc2_13_io_out_e),
    .io_in_l  (_LZC_enc2_12_io_out_e),
    .io_out_m (_LZC_Merge2_1_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_2 (
    .io_in_h  (_LZC_enc2_11_io_out_e),
    .io_in_l  (_LZC_enc2_10_io_out_e),
    .io_out_m (_LZC_Merge2_2_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_3 (
    .io_in_h  (_LZC_enc2_9_io_out_e),
    .io_in_l  (_LZC_enc2_8_io_out_e),
    .io_out_m (_LZC_Merge2_3_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_4 (
    .io_in_h  (_LZC_enc2_7_io_out_e),
    .io_in_l  (_LZC_enc2_6_io_out_e),
    .io_out_m (_LZC_Merge2_4_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_5 (
    .io_in_h  (_LZC_enc2_5_io_out_e),
    .io_in_l  (_LZC_enc2_4_io_out_e),
    .io_out_m (_LZC_Merge2_5_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_6 (
    .io_in_h  (_LZC_enc2_3_io_out_e),
    .io_in_l  (_LZC_enc2_2_io_out_e),
    .io_out_m (_LZC_Merge2_6_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_7 (
    .io_in_h  (_LZC_enc2_1_io_out_e),
    .io_in_l  (_LZC_enc2_io_out_e),
    .io_out_m (_LZC_Merge2_7_io_out_m)
  );
  LZC_Merge3 LZC_Merge3 (
    .io_in_h  (_LZC_Merge2_io_out_m),
    .io_in_l  (_LZC_Merge2_1_io_out_m),
    .io_out_m (_LZC_Merge3_io_out_m)
  );
  LZC_Merge3 LZC_Merge3_1 (
    .io_in_h  (_LZC_Merge2_2_io_out_m),
    .io_in_l  (_LZC_Merge2_3_io_out_m),
    .io_out_m (_LZC_Merge3_1_io_out_m)
  );
  LZC_Merge3 LZC_Merge3_2 (
    .io_in_h  (_LZC_Merge2_4_io_out_m),
    .io_in_l  (_LZC_Merge2_5_io_out_m),
    .io_out_m (_LZC_Merge3_2_io_out_m)
  );
  LZC_Merge3 LZC_Merge3_3 (
    .io_in_h  (_LZC_Merge2_6_io_out_m),
    .io_in_l  (_LZC_Merge2_7_io_out_m),
    .io_out_m (_LZC_Merge3_3_io_out_m)
  );
  LZC_Merge4 LZC_Merge4 (
    .io_in_h  (_LZC_Merge3_io_out_m),
    .io_in_l  (_LZC_Merge3_1_io_out_m),
    .io_out_m (_LZC_Merge4_io_out_m)
  );
  LZC_Merge4 LZC_Merge4_1 (
    .io_in_h  (_LZC_Merge3_2_io_out_m),
    .io_in_l  (_LZC_Merge3_3_io_out_m),
    .io_out_m (_LZC_Merge4_1_io_out_m)
  );
  LZC_Merge5 LZC_Merge5 (
    .io_in_h  (_LZC_Merge4_io_out_m),
    .io_in_l  (_LZC_Merge4_1_io_out_m),
    .io_out_m (io_out_c)
  );
endmodule

module FP_add_32_13(
  input         clock,
                io_in_en,
  input  [31:0] io_in_a,
                io_in_b,
  output [31:0] io_out_s
);

  wire [5:0]  _LZC32_2_io_out_c;
  wire [23:0] _full_adder_io_out_s;
  wire        _full_adder_io_out_c;
  wire [7:0]  _exp_subtractor_io_out_s;
  wire        _exp_subtractor_io_out_c;
  reg  [31:0] in_a;
  reg  [31:0] in_b;
  reg  [7:0]  exp_sr_0;
  reg  [7:0]  exp_sr_1;
  reg  [23:0] whole_frac_sr_0;
  reg  [23:0] whole_frac_sr_1;
  reg         sign_sr_0;
  reg         sign_sr_1;
  reg         exp_sub_out_c_r;
  reg         exp_sub_out_c;
  reg  [7:0]  exp_sub_out_s_r;
  reg  [7:0]  exp_sub_out_s;
  reg  [7:0]  exp_sr_2_r_0;
  reg  [7:0]  exp_sr_2_r_1;
  reg  [7:0]  exp_sr_2_0;
  reg  [7:0]  exp_sr_2_1;
  reg  [23:0] whole_frac_sr_2_r_0;
  reg  [23:0] whole_frac_sr_2_r_1;
  reg  [23:0] whole_frac_sr_2_0;
  reg  [23:0] whole_frac_sr_2_1;
  reg         sign_sr_2_r_0;
  reg         sign_sr_2_r_1;
  reg         sign_sr_2_0;
  reg         sign_sr_2_1;
  reg         eqexp_arrange;
  reg  [7:0]  exp_sr_3_0;
  reg  [7:0]  exp_sr_3_1;
  reg  [23:0] whole_frac_sr_3_0;
  reg  [23:0] whole_frac_sr_3_1;
  reg         sign_sr_3_0;
  reg         sign_sr_3_1;
  reg         exp_sub_out_c_2;
  reg  [7:0]  exp_sub_out_s_2;
  reg         redundant_op;
  reg  [23:0] fracadd_in_a;
  reg  [23:0] fracadd_in_b;
  reg  [7:0]  ref_exp;
  reg         ref_sign;
  reg         diff_sign;
  reg         frac_adder_out_c_r;
  reg         frac_adder_out_c;
  reg  [23:0] frac_adder_out_s_r;
  reg  [23:0] frac_adder_out_s;
  reg         diff_sign_2_r;
  reg         diff_sign_2;
  reg         redundant_op_2_r;
  reg         redundant_op_2;
  reg         ref_sign_2_r;
  reg         ref_sign_2;
  reg  [7:0]  ref_exp_2_r;
  reg  [7:0]  ref_exp_2;
  reg         sign_out;
  reg  [23:0] fracadd_outs;
  reg         fracadd_outc;
  reg         diff_sign_3;
  reg  [7:0]  ref_exp_3;
  reg  [5:0]  leadzeroindex;
  reg  [7:0]  ref_exp_4;
  reg  [23:0] fracadd_outs_2;
  reg         diff_sign_4;
  reg         fracadd_outc_2;
  reg         sign_out_2;
  reg         diff_sign_5;
  reg  [85:0] innermux_frac_true;
  reg  [22:0] innermux_frac_false;
  reg  [7:0]  innermux_exp_true;
  reg  [7:0]  innermux_exp_false;
  reg         sign_out_3;
  reg  [85:0] norm_out_frac_r;
  reg  [85:0] norm_out_frac_r_1;
  reg  [7:0]  norm_out_exp_r;
  reg  [7:0]  norm_out_exp;
  reg         norm_out_sign_r;
  reg         norm_out_sign;
  always @(posedge clock) begin
    if (io_in_en) begin
      automatic logic        _GEN = exp_sub_out_c_2 | eqexp_arrange;
      automatic logic [8:0]  _GEN_0 = {1'h0, ref_exp_4};
      automatic logic [8:0]  red = _GEN_0 - {3'h0, leadzeroindex};
      automatic logic [8:0]  inc = _GEN_0 + 9'h1;
      automatic logic [85:0] _GEN_1 = {63'h0, fracadd_outs_2[22:0]};
      automatic logic        _innermux_exp_true_T_2 = red == 9'h0;
      automatic logic        _innermux_exp_false_T_2 = inc > 9'hFE;
      in_a <= io_in_a;
      in_b <= io_in_b;
      exp_sr_0 <=
        {1'h0, in_a[30:23]} > 9'hFE ? 8'hFE : in_a[30:23] == 8'h0 ? 8'h1 : in_a[30:23];
      exp_sr_1 <=
        {1'h0, in_b[30:23]} > 9'hFE ? 8'hFE : in_b[30:23] == 8'h0 ? 8'h1 : in_b[30:23];
      whole_frac_sr_0 <= {1'h1, in_a[22:0]};
      whole_frac_sr_1 <= {1'h1, in_b[22:0]};
      sign_sr_0 <= in_a[31];
      sign_sr_1 <= in_b[31];
      exp_sub_out_c_r <= _exp_subtractor_io_out_c;
      exp_sub_out_c <= exp_sub_out_c_r;
      exp_sub_out_s_r <= _exp_subtractor_io_out_s;
      exp_sub_out_s <= exp_sub_out_s_r;
      exp_sr_2_r_0 <= exp_sr_0;
      exp_sr_2_r_1 <= exp_sr_1;
      exp_sr_2_0 <= exp_sr_2_r_0;
      exp_sr_2_1 <= exp_sr_2_r_1;
      whole_frac_sr_2_r_0 <= whole_frac_sr_0;
      whole_frac_sr_2_r_1 <= whole_frac_sr_1;
      whole_frac_sr_2_0 <= whole_frac_sr_2_r_0;
      whole_frac_sr_2_1 <= whole_frac_sr_2_r_1;
      sign_sr_2_r_0 <= sign_sr_0;
      sign_sr_2_r_1 <= sign_sr_1;
      sign_sr_2_0 <= sign_sr_2_r_0;
      sign_sr_2_1 <= sign_sr_2_r_1;
      eqexp_arrange <= exp_sr_2_0 == exp_sr_2_1 & whole_frac_sr_2_1 > whole_frac_sr_2_0;
      exp_sr_3_0 <= exp_sr_2_0;
      exp_sr_3_1 <= exp_sr_2_1;
      whole_frac_sr_3_0 <= whole_frac_sr_2_0;
      whole_frac_sr_3_1 <= whole_frac_sr_2_1;
      sign_sr_3_0 <= sign_sr_2_0;
      sign_sr_3_1 <= sign_sr_2_1;
      exp_sub_out_c_2 <= exp_sub_out_c;
      exp_sub_out_s_2 <= exp_sub_out_s;
      redundant_op <=
        (exp_sub_out_c_2 ? ~exp_sub_out_s_2 + 8'h1 : exp_sub_out_s_2) > 8'h17;
      fracadd_in_a <= _GEN ? whole_frac_sr_3_1 : whole_frac_sr_3_0;
      fracadd_in_b <=
        exp_sub_out_c_2
          ? whole_frac_sr_3_0 >> ~exp_sub_out_s_2 + 8'h1
          : (eqexp_arrange ? whole_frac_sr_3_0 : whole_frac_sr_3_1) >> exp_sub_out_s_2;
      ref_exp <= exp_sub_out_c_2 ? exp_sr_3_1 : exp_sr_3_0;
      ref_sign <= _GEN ? sign_sr_3_1 : sign_sr_3_0;
      diff_sign <= sign_sr_3_0 ^ sign_sr_3_1;
      frac_adder_out_c_r <= _full_adder_io_out_c;
      frac_adder_out_c <= frac_adder_out_c_r;
      frac_adder_out_s_r <= _full_adder_io_out_s;
      frac_adder_out_s <= frac_adder_out_s_r;
      diff_sign_2_r <= diff_sign;
      diff_sign_2 <= diff_sign_2_r;
      redundant_op_2_r <= redundant_op;
      redundant_op_2 <= redundant_op_2_r;
      ref_sign_2_r <= ref_sign;
      ref_sign_2 <= ref_sign_2_r;
      ref_exp_2_r <= ref_exp;
      ref_exp_2 <= ref_exp_2_r;
      sign_out <= diff_sign_2 & ~redundant_op_2 & ~frac_adder_out_c ^ ref_sign_2;
      fracadd_outs <= frac_adder_out_s;
      fracadd_outc <= frac_adder_out_c;
      diff_sign_3 <= diff_sign_2;
      ref_exp_3 <= ref_exp_2;
      leadzeroindex <= _LZC32_2_io_out_c;
      ref_exp_4 <= ref_exp_3;
      fracadd_outs_2 <= fracadd_outs;
      diff_sign_4 <= diff_sign_3;
      fracadd_outc_2 <= fracadd_outc;
      sign_out_2 <= sign_out;
      diff_sign_5 <= diff_sign_4;
      innermux_frac_true <=
        fracadd_outs_2[23]
          ? _GEN_1
          : red[8] | _innermux_exp_true_T_2 ? 86'h0 : _GEN_1 << leadzeroindex;
      innermux_frac_false <=
        fracadd_outc_2
          ? (inc[8] | _innermux_exp_false_T_2 ? 23'h7FFFFF : fracadd_outs_2[23:1])
          : fracadd_outs_2[22:0];
      innermux_exp_true <=
        fracadd_outs_2[23]
          ? ref_exp_4
          : red[8] | _innermux_exp_true_T_2 ? 8'h1 : red[7:0];
      innermux_exp_false <=
        fracadd_outc_2
          ? (inc[8] | _innermux_exp_false_T_2 ? 8'hFE : inc[7:0])
          : ref_exp_4;
      sign_out_3 <= sign_out_2;
      norm_out_frac_r <= diff_sign_5 ? innermux_frac_true : {63'h0, innermux_frac_false};
      norm_out_frac_r_1 <= norm_out_frac_r;
      norm_out_exp_r <= diff_sign_5 ? innermux_exp_true : innermux_exp_false;
      norm_out_exp <= norm_out_exp_r;
      norm_out_sign_r <= sign_out_3;
      norm_out_sign <= norm_out_sign_r;
    end
  end // always @(posedge)
  full_subtractor exp_subtractor (
    .io_in_a  (exp_sr_0),
    .io_in_b  (exp_sr_1),
    .io_out_s (_exp_subtractor_io_out_s),
    .io_out_c (_exp_subtractor_io_out_c)
  );
  full_adder full_adder (
    .io_in_a  (fracadd_in_a),
    .io_in_b  (diff_sign ? ~fracadd_in_b + 24'h1 : fracadd_in_b),
    .io_out_s (_full_adder_io_out_s),
    .io_out_c (_full_adder_io_out_c)
  );
  LZC32_2 LZC32_2 (
    .io_in_d  ({fracadd_outs, 8'hFF}),
    .io_out_c (_LZC32_2_io_out_c)
  );
  assign io_out_s = {norm_out_sign, norm_out_exp, norm_out_frac_r_1[22:0]};
endmodule

module complex_adder(
  input         clock,
  input  [63:0] io_complexA,
                io_complexB,
  input         io_in_en,
  output [63:0] io_out_s
);

  wire [31:0] _FP_adder_Inst_1_io_out_s;
  wire [31:0] _FP_adder_Inst_0_io_out_s;
  FP_add_32_13 FP_adder_Inst_0 (
    .clock    (clock),
    .io_in_en (io_in_en),
    .io_in_a  (io_complexA[63:32]),
    .io_in_b  (io_complexB[63:32]),
    .io_out_s (_FP_adder_Inst_0_io_out_s)
  );
  FP_add_32_13 FP_adder_Inst_1 (
    .clock    (clock),
    .io_in_en (io_in_en),
    .io_in_a  (io_complexA[31:0]),
    .io_in_b  (io_complexB[31:0]),
    .io_out_s (_FP_adder_Inst_1_io_out_s)
  );
  assign io_out_s = {_FP_adder_Inst_0_io_out_s, _FP_adder_Inst_1_io_out_s};
endmodule

module vk_gen(
  input         clock,
                reset,
  input  [63:0] io_xk_in_0,
                io_xk_in_1,
                io_alpha_in,
  input         io_in_en,
                io_counter_reset,
  output [63:0] io_out_s_0,
                io_out_s_1
);

  wire [63:0] _adder_io_out_s;
  reg  [31:0] counter;
  wire        _GEN = counter == 32'h0;
  reg  [63:0] shifted_xk_r;
  reg  [63:0] shifted_xk_r_1;
  reg  [63:0] shifted_xk_r_2;
  reg  [63:0] shifted_xk_r_3;
  reg  [63:0] shifted_xk_r_4;
  reg  [63:0] shifted_xk_r_5;
  reg  [63:0] shifted_xk_r_6;
  reg  [63:0] shifted_xk_r_7;
  reg  [63:0] shifted_xk_r_8;
  reg  [63:0] shifted_xk_r_9;
  reg  [63:0] shifted_xk_r_10;
  reg  [63:0] shifted_xk_r_11;
  reg  [63:0] shifted_xk_r_12;
  reg  [63:0] shifted_xk_r_13;
  reg  [63:0] shifted_xk_r_14;
  reg  [63:0] shifted_xk_r_15;
  reg  [63:0] shifted_xk_r_16;
  reg  [63:0] shifted_xk_r_17;
  reg  [63:0] shifted_xk_r_18;
  reg  [63:0] shifted_xk_r_19;
  reg  [63:0] shifted_xk_r_20;
  reg  [63:0] shifted_xk_r_21;
  reg  [63:0] shifted_xk_r_22;
  reg  [63:0] shifted_xk_r_23;
  reg  [63:0] shifted_xk_r_24;
  reg  [63:0] shifted_xk_r_25;
  always @(posedge clock) begin
    if (reset)
      counter <= 32'h0;
    else if (io_counter_reset)
      counter <= 32'h0;
    else if (io_in_en)
      counter <= counter + 32'h1;
    shifted_xk_r <= io_xk_in_0;
    shifted_xk_r_1 <= shifted_xk_r;
    shifted_xk_r_2 <= shifted_xk_r_1;
    shifted_xk_r_3 <= shifted_xk_r_2;
    shifted_xk_r_4 <= shifted_xk_r_3;
    shifted_xk_r_5 <= shifted_xk_r_4;
    shifted_xk_r_6 <= shifted_xk_r_5;
    shifted_xk_r_7 <= shifted_xk_r_6;
    shifted_xk_r_8 <= shifted_xk_r_7;
    shifted_xk_r_9 <= shifted_xk_r_8;
    shifted_xk_r_10 <= shifted_xk_r_9;
    shifted_xk_r_11 <= shifted_xk_r_10;
    shifted_xk_r_12 <= shifted_xk_r_11;
    shifted_xk_r_13 <= io_xk_in_1;
    shifted_xk_r_14 <= shifted_xk_r_13;
    shifted_xk_r_15 <= shifted_xk_r_14;
    shifted_xk_r_16 <= shifted_xk_r_15;
    shifted_xk_r_17 <= shifted_xk_r_16;
    shifted_xk_r_18 <= shifted_xk_r_17;
    shifted_xk_r_19 <= shifted_xk_r_18;
    shifted_xk_r_20 <= shifted_xk_r_19;
    shifted_xk_r_21 <= shifted_xk_r_20;
    shifted_xk_r_22 <= shifted_xk_r_21;
    shifted_xk_r_23 <= shifted_xk_r_22;
    shifted_xk_r_24 <= shifted_xk_r_23;
    shifted_xk_r_25 <= shifted_xk_r_24;
  end // always @(posedge)
  complex_adder adder (
    .clock       (clock),
    .io_complexA (_GEN ? io_xk_in_0 : 64'h0),
    .io_complexB (_GEN ? io_alpha_in : 64'h0),
    .io_in_en    (1'h1),
    .io_out_s    (_adder_io_out_s)
  );
  assign io_out_s_0 = counter == 32'hD ? _adder_io_out_s : shifted_xk_r_12;
  assign io_out_s_1 = shifted_xk_r_25;
endmodule

module full_adder_2(
  input  [7:0] io_in_a,
               io_in_b,
  output [7:0] io_out_s,
  output       io_out_c
);

  wire [8:0] result = {1'h0, io_in_a} + {1'h0, io_in_b};
  assign io_out_s = result[7:0];
  assign io_out_c = result[8];
endmodule

module multiplier(
  input  [23:0] io_in_a,
                io_in_b,
  output [47:0] io_out_s
);

  assign io_out_s = {24'h0, io_in_a} * {24'h0, io_in_b};
endmodule

module FP_mult_32_10_v2(
  input         clock,
                io_in_en,
  input  [31:0] io_in_a,
                io_in_b,
  output [31:0] io_out_s
);

  wire [47:0] _multiplier_io_out_s;
  wire [7:0]  _exp_adder_io_out_s;
  wire        _exp_adder_io_out_c;
  reg  [31:0] in_a;
  reg  [31:0] in_b;
  reg  [23:0] whole_frac_sr_0;
  reg  [23:0] whole_frac_sr_1;
  reg         sign_sr_0;
  reg         sign_sr_1;
  reg  [7:0]  exp_sr_0;
  reg  [7:0]  exp_sr_1;
  reg         new_sign_sr;
  reg  [7:0]  exp_sr_2_0;
  reg  [7:0]  exp_sr_2_1;
  reg  [23:0] whole_frac_sr_2_0;
  reg  [23:0] whole_frac_sr_2_1;
  reg  [7:0]  exp_adder_outs_sr;
  reg         exp_adder_outc_sr;
  reg         new_sign_sr_2;
  reg  [7:0]  exp_sr_3_1;
  reg  [23:0] whole_frac_sr_3_0;
  reg  [23:0] whole_frac_sr_3_1;
  reg  [47:0] frac_mult_out_sr;
  reg  [7:0]  exp_adder_outs_sr_2;
  reg         exp_adder_outc_sr_2;
  reg         new_sign_sr_3;
  reg  [7:0]  exp_sr_4_1;
  reg  [7:0]  uo_check_r;
  reg         carry_flag;
  reg  [7:0]  exp_sum;
  reg         new_sign_reg;
  reg         msb_check;
  reg  [47:0] new_frac_reg;
  reg         u_flag_reg;
  reg         o_flag_reg;
  reg  [7:0]  new_exp_reg;
  reg         new_sign_reg_2;
  reg  [47:0] new_frac_reg_2;
  reg  [7:0]  out_exp_innermux;
  reg  [22:0] out_frac_innermux;
  reg         u_flag_reg_2;
  reg         o_flag_reg_2;
  reg         new_sign_reg_3;
  reg  [7:0]  out_exp_innermux_2;
  reg  [22:0] out_frac_innermux_2;
  reg         new_sign_reg_4;
  reg         u_flag_reg_3;
  reg  [31:0] io_out_s_r;
  always @(posedge clock) begin
    if (io_in_en) begin
      automatic logic       uo_check = uo_check_r < 8'h7F;
      automatic logic [8:0] _o_flag_reg_T_1 = {1'h0, exp_sum} + {8'h0, msb_check};
      in_a <= io_in_a;
      in_b <= io_in_b;
      whole_frac_sr_0 <= {1'h1, in_a[22:0]};
      whole_frac_sr_1 <= {1'h1, in_b[22:0]};
      sign_sr_0 <= in_a[31];
      sign_sr_1 <= in_b[31];
      exp_sr_0 <= (&(in_a[30:23])) ? 8'hFE : in_a[30:23] == 8'h0 ? 8'h1 : in_a[30:23];
      exp_sr_1 <= (&(in_b[30:23])) ? 8'hFE : in_b[30:23] == 8'h0 ? 8'h1 : in_b[30:23];
      new_sign_sr <= sign_sr_0 ^ sign_sr_1;
      exp_sr_2_0 <= exp_sr_0;
      exp_sr_2_1 <= exp_sr_1;
      whole_frac_sr_2_0 <= whole_frac_sr_0;
      whole_frac_sr_2_1 <= whole_frac_sr_1;
      exp_adder_outs_sr <= _exp_adder_io_out_s;
      exp_adder_outc_sr <= _exp_adder_io_out_c;
      new_sign_sr_2 <= new_sign_sr;
      exp_sr_3_1 <= exp_sr_2_1;
      whole_frac_sr_3_0 <= whole_frac_sr_2_0;
      whole_frac_sr_3_1 <= whole_frac_sr_2_1;
      frac_mult_out_sr <= _multiplier_io_out_s;
      exp_adder_outs_sr_2 <= exp_adder_outs_sr;
      exp_adder_outc_sr_2 <= exp_adder_outc_sr;
      new_sign_sr_3 <= new_sign_sr_2;
      exp_sr_4_1 <= exp_sr_3_1;
      uo_check_r <= exp_sr_4_1;
      carry_flag <= exp_adder_outc_sr_2;
      exp_sum <= exp_adder_outs_sr_2;
      new_sign_reg <= new_sign_sr_3;
      msb_check <= frac_mult_out_sr[47];
      new_frac_reg <= frac_mult_out_sr;
      u_flag_reg <= uo_check & (~carry_flag | _o_flag_reg_T_1 == 9'h0);
      o_flag_reg <= ~uo_check & (carry_flag | _o_flag_reg_T_1 > 9'hFE);
      new_exp_reg <= exp_sum;
      new_sign_reg_2 <= new_sign_reg;
      new_frac_reg_2 <= new_frac_reg;
      out_exp_innermux <= new_frac_reg_2[47] ? new_exp_reg + 8'h1 : new_exp_reg;
      out_frac_innermux <=
        new_frac_reg_2[47] ? new_frac_reg_2[46:24] : new_frac_reg_2[45:23];
      u_flag_reg_2 <= u_flag_reg;
      o_flag_reg_2 <= o_flag_reg;
      new_sign_reg_3 <= new_sign_reg_2;
      out_exp_innermux_2 <= o_flag_reg_2 ? 8'hFE : out_exp_innermux;
      out_frac_innermux_2 <= o_flag_reg_2 ? 23'h7FFFFF : out_frac_innermux;
      new_sign_reg_4 <= new_sign_reg_3;
      u_flag_reg_3 <= u_flag_reg_2;
      io_out_s_r <=
        {new_sign_reg_4,
         u_flag_reg_3 ? 8'h1 : out_exp_innermux_2,
         u_flag_reg_3 ? 23'h0 : out_frac_innermux_2};
    end
  end // always @(posedge)
  full_adder_2 exp_adder (
    .io_in_a  (exp_sr_2_0),
    .io_in_b  (exp_sr_2_1 - 8'h7F),
    .io_out_s (_exp_adder_io_out_s),
    .io_out_c (_exp_adder_io_out_c)
  );
  multiplier multiplier (
    .io_in_a  (whole_frac_sr_3_0),
    .io_in_b  (whole_frac_sr_3_1),
    .io_out_s (_multiplier_io_out_s)
  );
  assign io_out_s = io_out_s_r;
endmodule

module complex_conjugate_mult(
  input         clock,
                reset,
  input  [63:0] io_complexA,
                io_complexB,
  input         io_in_en,
                io_counter_rest,
  output [63:0] io_out_s
);

  wire        _GEN;
  wire [31:0] _FP_adder_Inst_1_io_out_s;
  wire [31:0] _FP_adder_Inst_0_io_out_s;
  wire [31:0] _FP_mult_inst_3_io_out_s;
  wire [31:0] _FP_mult_inst_2_io_out_s;
  wire [31:0] _FP_mult_inst_1_io_out_s;
  wire [31:0] _FP_mult_inst_0_io_out_s;
  reg  [15:0] counter;
  assign _GEN = io_in_en & counter > 16'h9;
  always @(posedge clock) begin
    if (reset)
      counter <= 16'h0;
    else if (io_counter_rest)
      counter <= 16'h0;
    else if (io_in_en)
      counter <= counter + 16'h1;
  end // always @(posedge)
  FP_mult_32_10_v2 FP_mult_inst_0 (
    .clock    (clock),
    .io_in_en (io_in_en),
    .io_in_a  (io_complexA[63:32]),
    .io_in_b  (io_complexB[63:32]),
    .io_out_s (_FP_mult_inst_0_io_out_s)
  );
  FP_mult_32_10_v2 FP_mult_inst_1 (
    .clock    (clock),
    .io_in_en (io_in_en),
    .io_in_a  (io_complexA[31:0]),
    .io_in_b  (io_complexB[31:0]),
    .io_out_s (_FP_mult_inst_1_io_out_s)
  );
  FP_mult_32_10_v2 FP_mult_inst_2 (
    .clock    (clock),
    .io_in_en (io_in_en),
    .io_in_a  (io_complexA[31:0]),
    .io_in_b  (io_complexB[63:32]),
    .io_out_s (_FP_mult_inst_2_io_out_s)
  );
  FP_mult_32_10_v2 FP_mult_inst_3 (
    .clock    (clock),
    .io_in_en (io_in_en),
    .io_in_a  (io_complexA[63:32]),
    .io_in_b  (io_complexB[31:0]),
    .io_out_s (_FP_mult_inst_3_io_out_s)
  );
  FP_add_32_13 FP_adder_Inst_0 (
    .clock    (clock),
    .io_in_en (_GEN),
    .io_in_a  (_GEN ? _FP_mult_inst_0_io_out_s : 32'h0),
    .io_in_b  (_GEN ? _FP_mult_inst_1_io_out_s : 32'h0),
    .io_out_s (_FP_adder_Inst_0_io_out_s)
  );
  FP_add_32_13 FP_adder_Inst_1 (
    .clock    (clock),
    .io_in_en (_GEN),
    .io_in_a  (_GEN ? _FP_mult_inst_2_io_out_s ^ 32'h80000000 : 32'h0),
    .io_in_b  (_GEN ? _FP_mult_inst_3_io_out_s : 32'h0),
    .io_out_s (_FP_adder_Inst_1_io_out_s)
  );
  assign io_out_s = {_FP_adder_Inst_0_io_out_s, _FP_adder_Inst_1_io_out_s};
endmodule

module complex_dot_streaming(
  input         clock,
                reset,
  input  [63:0] io_vec_a_0,
                io_vec_a_1,
                io_vec_b_0,
                io_vec_b_1,
  input         io_in_en,
                io_counter_reset,
  output [63:0] io_out_s
);

  wire [63:0] _adderInst_io_out_s;
  wire [63:0] _MultInst_1_io_out_s;
  wire [63:0] _MultInst_io_out_s;
  complex_conjugate_mult MultInst (
    .clock           (clock),
    .reset           (reset),
    .io_complexA     (io_vec_a_0),
    .io_complexB     (io_vec_b_0),
    .io_in_en        (io_in_en),
    .io_counter_rest (io_counter_reset),
    .io_out_s        (_MultInst_io_out_s)
  );
  complex_conjugate_mult MultInst_1 (
    .clock           (clock),
    .reset           (reset),
    .io_complexA     (io_vec_a_1),
    .io_complexB     (io_vec_b_1),
    .io_in_en        (io_in_en),
    .io_counter_rest (io_counter_reset),
    .io_out_s        (_MultInst_1_io_out_s)
  );
  complex_adder adderInst (
    .clock       (clock),
    .io_complexA (_MultInst_io_out_s),
    .io_complexB (_MultInst_1_io_out_s),
    .io_in_en    (io_in_en),
    .io_out_s    (_adderInst_io_out_s)
  );
  assign io_out_s = io_in_en ? _adderInst_io_out_s : 64'h0;
endmodule

module demux1(
  input  [63:0] io_input,
  input         io_sel,
  output [63:0] io_outputs_0,
                io_outputs_1
);

  assign io_outputs_0 = io_sel ? 64'h0 : io_input;
  assign io_outputs_1 = io_sel ? io_input : 64'h0;
endmodule

module complex_acc(
  input         clock,
                reset,
  input  [63:0] io_input,
  input         io_in_en,
                io_counter_reset,
  output [63:0] io_output
);

  wire [63:0] _demux1_io_outputs_0;
  wire [63:0] _demux1_io_outputs_1;
  reg  [31:0] counter;
  reg         adder_io_in_en_r;
  reg  [63:0] adder_io_complexA_r;
  always @(posedge clock) begin
    if (reset)
      counter <= 32'h0;
    else if (io_counter_reset)
      counter <= 32'h0;
    else if (io_in_en)
      counter <= counter + 32'h1;
    adder_io_in_en_r <= io_in_en;
    adder_io_complexA_r <= _demux1_io_outputs_0;
  end // always @(posedge)
  demux1 demux1 (
    .io_input     (io_input),
    .io_sel       (counter[0]),
    .io_outputs_0 (_demux1_io_outputs_0),
    .io_outputs_1 (_demux1_io_outputs_1)
  );
  complex_adder adder (
    .clock       (clock),
    .io_complexA (adder_io_complexA_r),
    .io_complexB (_demux1_io_outputs_1),
    .io_in_en    (adder_io_in_en_r),
    .io_out_s    (io_output)
  );
endmodule

module cmplx_dot_iterative(
  input         clock,
                reset,
  input  [63:0] io_vec_a_0,
                io_vec_a_1,
                io_vec_b_0,
                io_vec_b_1,
  input         io_counter_reset,
                io_in_en,
  output [31:0] io_out_real,
                io_out_imag
);

  wire [63:0] _d2aInst_0_io_output;
  wire [63:0] _complex_dot_io_out_s;
  reg  [31:0] counter;
  reg         index;
  wire        _GEN = counter > 32'h23;
  always @(posedge clock) begin
    if (reset) begin
      counter <= 32'h0;
      index <= 1'h0;
    end
    else begin
      if (io_counter_reset)
        counter <= 32'h0;
      else if (io_in_en)
        counter <= counter + 32'h1;
      index <= index - 1'h1;
    end
  end // always @(posedge)
  complex_dot_streaming complex_dot (
    .clock            (clock),
    .reset            (reset),
    .io_vec_a_0       (io_vec_a_0),
    .io_vec_a_1       (io_vec_a_1),
    .io_vec_b_0       (io_vec_b_0),
    .io_vec_b_1       (io_vec_b_1),
    .io_in_en         (io_in_en),
    .io_counter_reset (io_counter_reset),
    .io_out_s         (_complex_dot_io_out_s)
  );
  complex_acc d2aInst_0 (
    .clock            (clock),
    .reset            (reset),
    .io_input         (_complex_dot_io_out_s),
    .io_in_en         (_GEN),
    .io_counter_reset (_GEN & io_counter_reset),
    .io_output        (_d2aInst_0_io_output)
  );
  assign io_out_real = _d2aInst_0_io_output[63:32];
  assign io_out_imag = _d2aInst_0_io_output[31:0];
endmodule

module complex_mult(
  input         clock,
                reset,
  input  [63:0] io_complexA,
                io_complexB,
  output [63:0] io_out_s
);

  wire        _GEN;
  wire [31:0] _FP_adder_Inst_1_io_out_s;
  wire [31:0] _FP_adder_Inst_0_io_out_s;
  wire [31:0] _FP_mult_inst_3_io_out_s;
  wire [31:0] _FP_mult_inst_2_io_out_s;
  wire [31:0] _FP_mult_inst_1_io_out_s;
  wire [31:0] _FP_mult_inst_0_io_out_s;
  reg  [15:0] counter;
  assign _GEN = counter > 16'h9;
  always @(posedge clock) begin
    if (reset)
      counter <= 16'h0;
    else
      counter <= counter + 16'h1;
  end // always @(posedge)
  FP_mult_32_10_v2 FP_mult_inst_0 (
    .clock    (clock),
    .io_in_en (1'h1),
    .io_in_a  (io_complexA[63:32]),
    .io_in_b  (io_complexB[63:32]),
    .io_out_s (_FP_mult_inst_0_io_out_s)
  );
  FP_mult_32_10_v2 FP_mult_inst_1 (
    .clock    (clock),
    .io_in_en (1'h1),
    .io_in_a  (io_complexA[31:0]),
    .io_in_b  (io_complexB[31:0]),
    .io_out_s (_FP_mult_inst_1_io_out_s)
  );
  FP_mult_32_10_v2 FP_mult_inst_2 (
    .clock    (clock),
    .io_in_en (1'h1),
    .io_in_a  (io_complexA[31:0]),
    .io_in_b  (io_complexB[63:32]),
    .io_out_s (_FP_mult_inst_2_io_out_s)
  );
  FP_mult_32_10_v2 FP_mult_inst_3 (
    .clock    (clock),
    .io_in_en (1'h1),
    .io_in_a  (io_complexA[63:32]),
    .io_in_b  (io_complexB[31:0]),
    .io_out_s (_FP_mult_inst_3_io_out_s)
  );
  FP_add_32_13 FP_adder_Inst_0 (
    .clock    (clock),
    .io_in_en (_GEN),
    .io_in_a  (_GEN ? _FP_mult_inst_0_io_out_s : 32'h0),
    .io_in_b  (_GEN ? _FP_mult_inst_1_io_out_s ^ 32'h80000000 : 32'h0),
    .io_out_s (_FP_adder_Inst_0_io_out_s)
  );
  FP_add_32_13 FP_adder_Inst_1 (
    .clock    (clock),
    .io_in_en (_GEN),
    .io_in_a  (_GEN ? _FP_mult_inst_2_io_out_s : 32'h0),
    .io_in_b  (_GEN ? _FP_mult_inst_3_io_out_s : 32'h0),
    .io_out_s (_FP_adder_Inst_1_io_out_s)
  );
  assign io_out_s = {_FP_adder_Inst_0_io_out_s, _FP_adder_Inst_1_io_out_s};
endmodule

module iterative_axpy(
  input         clock,
                reset,
  input  [63:0] io_s_in,
                io_vk_in_0,
                io_vk_in_1,
                io_xk_in_0,
                io_xk_in_1,
  input         io_en_in,
  output [63:0] io_out_s_0,
                io_out_s_1
);

  wire [63:0] _mult_1_io_out_s;
  wire [63:0] _mult_0_io_out_s;
  reg  [31:0] counter;
  wire        _GEN = counter > 32'h16;
  wire        _GEN_0 = _GEN | io_en_in;
  reg  [63:0] adder_0_io_complexA_r;
  reg  [63:0] adder_0_io_complexA_r_1;
  reg  [63:0] adder_0_io_complexA_r_2;
  reg  [63:0] adder_0_io_complexA_r_3;
  reg  [63:0] adder_0_io_complexA_r_4;
  reg  [63:0] adder_0_io_complexA_r_5;
  reg  [63:0] adder_0_io_complexA_r_6;
  reg  [63:0] adder_0_io_complexA_r_7;
  reg  [63:0] adder_0_io_complexA_r_8;
  reg  [63:0] adder_0_io_complexA_r_9;
  reg  [63:0] adder_0_io_complexA_r_10;
  reg  [63:0] adder_0_io_complexA_r_11;
  reg  [63:0] adder_0_io_complexA_r_12;
  reg  [63:0] adder_0_io_complexA_r_13;
  reg  [63:0] adder_0_io_complexA_r_14;
  reg  [63:0] adder_0_io_complexA_r_15;
  reg  [63:0] adder_0_io_complexA_r_16;
  reg  [63:0] adder_0_io_complexA_r_17;
  reg  [63:0] adder_0_io_complexA_r_18;
  reg  [63:0] adder_0_io_complexA_r_19;
  reg  [63:0] adder_0_io_complexA_r_20;
  reg  [63:0] adder_0_io_complexA_r_21;
  reg  [63:0] adder_0_io_complexA_r_22;
  reg  [63:0] adder_1_io_complexA_r;
  reg  [63:0] adder_1_io_complexA_r_1;
  reg  [63:0] adder_1_io_complexA_r_2;
  reg  [63:0] adder_1_io_complexA_r_3;
  reg  [63:0] adder_1_io_complexA_r_4;
  reg  [63:0] adder_1_io_complexA_r_5;
  reg  [63:0] adder_1_io_complexA_r_6;
  reg  [63:0] adder_1_io_complexA_r_7;
  reg  [63:0] adder_1_io_complexA_r_8;
  reg  [63:0] adder_1_io_complexA_r_9;
  reg  [63:0] adder_1_io_complexA_r_10;
  reg  [63:0] adder_1_io_complexA_r_11;
  reg  [63:0] adder_1_io_complexA_r_12;
  reg  [63:0] adder_1_io_complexA_r_13;
  reg  [63:0] adder_1_io_complexA_r_14;
  reg  [63:0] adder_1_io_complexA_r_15;
  reg  [63:0] adder_1_io_complexA_r_16;
  reg  [63:0] adder_1_io_complexA_r_17;
  reg  [63:0] adder_1_io_complexA_r_18;
  reg  [63:0] adder_1_io_complexA_r_19;
  reg  [63:0] adder_1_io_complexA_r_20;
  reg  [63:0] adder_1_io_complexA_r_21;
  reg  [63:0] adder_1_io_complexA_r_22;
  always @(posedge clock) begin
    if (reset)
      counter <= 32'h0;
    else if (io_en_in)
      counter <= counter + 32'h1;
    adder_0_io_complexA_r <= io_xk_in_0;
    adder_0_io_complexA_r_1 <= adder_0_io_complexA_r;
    adder_0_io_complexA_r_2 <= adder_0_io_complexA_r_1;
    adder_0_io_complexA_r_3 <= adder_0_io_complexA_r_2;
    adder_0_io_complexA_r_4 <= adder_0_io_complexA_r_3;
    adder_0_io_complexA_r_5 <= adder_0_io_complexA_r_4;
    adder_0_io_complexA_r_6 <= adder_0_io_complexA_r_5;
    adder_0_io_complexA_r_7 <= adder_0_io_complexA_r_6;
    adder_0_io_complexA_r_8 <= adder_0_io_complexA_r_7;
    adder_0_io_complexA_r_9 <= adder_0_io_complexA_r_8;
    adder_0_io_complexA_r_10 <= adder_0_io_complexA_r_9;
    adder_0_io_complexA_r_11 <= adder_0_io_complexA_r_10;
    adder_0_io_complexA_r_12 <= adder_0_io_complexA_r_11;
    adder_0_io_complexA_r_13 <= adder_0_io_complexA_r_12;
    adder_0_io_complexA_r_14 <= adder_0_io_complexA_r_13;
    adder_0_io_complexA_r_15 <= adder_0_io_complexA_r_14;
    adder_0_io_complexA_r_16 <= adder_0_io_complexA_r_15;
    adder_0_io_complexA_r_17 <= adder_0_io_complexA_r_16;
    adder_0_io_complexA_r_18 <= adder_0_io_complexA_r_17;
    adder_0_io_complexA_r_19 <= adder_0_io_complexA_r_18;
    adder_0_io_complexA_r_20 <= adder_0_io_complexA_r_19;
    adder_0_io_complexA_r_21 <= adder_0_io_complexA_r_20;
    adder_0_io_complexA_r_22 <= adder_0_io_complexA_r_21;
    adder_1_io_complexA_r <= io_xk_in_1;
    adder_1_io_complexA_r_1 <= adder_1_io_complexA_r;
    adder_1_io_complexA_r_2 <= adder_1_io_complexA_r_1;
    adder_1_io_complexA_r_3 <= adder_1_io_complexA_r_2;
    adder_1_io_complexA_r_4 <= adder_1_io_complexA_r_3;
    adder_1_io_complexA_r_5 <= adder_1_io_complexA_r_4;
    adder_1_io_complexA_r_6 <= adder_1_io_complexA_r_5;
    adder_1_io_complexA_r_7 <= adder_1_io_complexA_r_6;
    adder_1_io_complexA_r_8 <= adder_1_io_complexA_r_7;
    adder_1_io_complexA_r_9 <= adder_1_io_complexA_r_8;
    adder_1_io_complexA_r_10 <= adder_1_io_complexA_r_9;
    adder_1_io_complexA_r_11 <= adder_1_io_complexA_r_10;
    adder_1_io_complexA_r_12 <= adder_1_io_complexA_r_11;
    adder_1_io_complexA_r_13 <= adder_1_io_complexA_r_12;
    adder_1_io_complexA_r_14 <= adder_1_io_complexA_r_13;
    adder_1_io_complexA_r_15 <= adder_1_io_complexA_r_14;
    adder_1_io_complexA_r_16 <= adder_1_io_complexA_r_15;
    adder_1_io_complexA_r_17 <= adder_1_io_complexA_r_16;
    adder_1_io_complexA_r_18 <= adder_1_io_complexA_r_17;
    adder_1_io_complexA_r_19 <= adder_1_io_complexA_r_18;
    adder_1_io_complexA_r_20 <= adder_1_io_complexA_r_19;
    adder_1_io_complexA_r_21 <= adder_1_io_complexA_r_20;
    adder_1_io_complexA_r_22 <= adder_1_io_complexA_r_21;
  end // always @(posedge)
  complex_mult mult_0 (
    .clock       (clock),
    .reset       (reset),
    .io_complexA (io_s_in),
    .io_complexB (io_vk_in_0),
    .io_out_s    (_mult_0_io_out_s)
  );
  complex_mult mult_1 (
    .clock       (clock),
    .reset       (reset),
    .io_complexA (io_s_in),
    .io_complexB (io_vk_in_1),
    .io_out_s    (_mult_1_io_out_s)
  );
  complex_adder adder_0 (
    .clock       (clock),
    .io_complexA (_GEN ? adder_0_io_complexA_r_22 : 64'h0),
    .io_complexB (_GEN ? _mult_0_io_out_s : 64'h0),
    .io_in_en    (_GEN_0),
    .io_out_s    (io_out_s_0)
  );
  complex_adder adder_1 (
    .clock       (clock),
    .io_complexA (_GEN ? adder_1_io_complexA_r_22 : 64'h0),
    .io_complexB (_GEN ? _mult_1_io_out_s : 64'h0),
    .io_in_en    (_GEN_0),
    .io_out_s    (io_out_s_1)
  );
endmodule

module tsqr_inner_loop(
  input         clock,
                reset,
  input  [63:0] io_xk_in_0,
                io_xk_in_1,
                io_alpha_in,
  input  [31:0] io_tk_in,
  input  [1:0]  io_column_count,
  input         io_en_in,
                io_valid_in,
                io_counter_reset,
  output        io_valid_out,
                io_col2_done,
                io_updates_done,
  output [63:0] io_out_s_0,
                io_out_s_1
);

  wire [31:0]      _mult_1_io_out_s;
  wire [31:0]      _mult_0_io_out_s;
  wire [31:0]      _dot_io_out_real;
  wire [31:0]      _dot_io_out_imag;
  wire [63:0]      _vk_io_out_s_0;
  wire [63:0]      _vk_io_out_s_1;
  reg  [63:0]      vk_reg_0;
  reg  [63:0]      vk_reg_1;
  reg  [63:0]      vk_reg_2;
  reg  [63:0]      vk_reg_3;
  reg  [31:0]      tk_reg;
  reg  [31:0]      counter;
  reg  [1:0]       index;
  wire             _GEN = counter > 32'hC;
  wire             _GEN_0 = counter < 32'hF;
  reg  [1:0]       index_2;
  wire [3:0][63:0] _GEN_1 = {{vk_reg_3}, {vk_reg_2}, {vk_reg_1}, {vk_reg_0}};
  reg  [63:0]      r_0;
  reg  [63:0]      r_1;
  reg  [63:0]      r_1_0;
  reg  [63:0]      r_1_1;
  reg  [63:0]      r_2_0;
  reg  [63:0]      r_2_1;
  reg  [63:0]      r_3_0;
  reg  [63:0]      r_3_1;
  reg  [63:0]      r_4_0;
  reg  [63:0]      r_4_1;
  reg  [63:0]      r_5_0;
  reg  [63:0]      r_5_1;
  reg  [63:0]      r_6_0;
  reg  [63:0]      r_6_1;
  reg  [63:0]      r_7_0;
  reg  [63:0]      r_7_1;
  reg  [63:0]      r_8_0;
  reg  [63:0]      r_8_1;
  reg  [63:0]      r_9_0;
  reg  [63:0]      r_9_1;
  reg  [63:0]      r_10_0;
  reg  [63:0]      r_10_1;
  reg  [63:0]      r_11_0;
  reg  [63:0]      r_11_1;
  reg  [63:0]      r_12_0;
  reg  [63:0]      r_12_1;
  wire             _GEN_2 = counter > 32'h3E;
  wire             _GEN_3 = _GEN_2 | io_en_in;
  wire [31:0]      _GEN_4 = _GEN_2 ? tk_reg : 32'h0;
  reg  [63:0]      scalar_reg;
  reg  [1:0]       index2;
  wire             _GEN_5 = counter > 32'h49;
  reg  [63:0]      r_13_0;
  reg  [63:0]      r_13_1;
  reg  [63:0]      r_14_0;
  reg  [63:0]      r_14_1;
  reg  [63:0]      r_15_0;
  reg  [63:0]      r_15_1;
  reg  [63:0]      r_16_0;
  reg  [63:0]      r_16_1;
  reg  [63:0]      r_17_0;
  reg  [63:0]      r_17_1;
  reg  [63:0]      r_18_0;
  reg  [63:0]      r_18_1;
  reg  [63:0]      r_19_0;
  reg  [63:0]      r_19_1;
  reg  [63:0]      r_20_0;
  reg  [63:0]      r_20_1;
  reg  [63:0]      r_21_0;
  reg  [63:0]      r_21_1;
  reg  [63:0]      r_22_0;
  reg  [63:0]      r_22_1;
  reg  [63:0]      r_23_0;
  reg  [63:0]      r_23_1;
  reg  [63:0]      r_24_0;
  reg  [63:0]      r_24_1;
  reg  [63:0]      r_25_0;
  reg  [63:0]      r_25_1;
  reg  [63:0]      r_26_0;
  reg  [63:0]      r_26_1;
  reg  [63:0]      r_27_0;
  reg  [63:0]      r_27_1;
  reg  [63:0]      r_28_0;
  reg  [63:0]      r_28_1;
  reg  [63:0]      r_29_0;
  reg  [63:0]      r_29_1;
  reg  [63:0]      r_30_0;
  reg  [63:0]      r_30_1;
  reg  [63:0]      r_31_0;
  reg  [63:0]      r_31_1;
  reg  [63:0]      r_32_0;
  reg  [63:0]      r_32_1;
  reg  [63:0]      r_33_0;
  reg  [63:0]      r_33_1;
  reg  [63:0]      r_34_0;
  reg  [63:0]      r_34_1;
  reg  [63:0]      r_35_0;
  reg  [63:0]      r_35_1;
  reg  [63:0]      r_36_0;
  reg  [63:0]      r_36_1;
  reg  [63:0]      r_37_0;
  reg  [63:0]      r_37_1;
  reg  [63:0]      r_38_0;
  reg  [63:0]      r_38_1;
  reg  [63:0]      r_39_0;
  reg  [63:0]      r_39_1;
  reg  [63:0]      r_40_0;
  reg  [63:0]      r_40_1;
  reg  [63:0]      r_41_0;
  reg  [63:0]      r_41_1;
  reg  [63:0]      r_42_0;
  reg  [63:0]      r_42_1;
  reg  [63:0]      r_43_0;
  reg  [63:0]      r_43_1;
  reg  [63:0]      r_44_0;
  reg  [63:0]      r_44_1;
  reg  [63:0]      r_45_0;
  reg  [63:0]      r_45_1;
  reg  [63:0]      r_46_0;
  reg  [63:0]      r_46_1;
  reg  [63:0]      r_47_0;
  reg  [63:0]      r_47_1;
  reg  [63:0]      r_48_0;
  reg  [63:0]      r_48_1;
  reg  [63:0]      r_49_0;
  reg  [63:0]      r_49_1;
  reg  [63:0]      r_50_0;
  reg  [63:0]      r_50_1;
  reg  [63:0]      r_51_0;
  reg  [63:0]      r_51_1;
  reg  [63:0]      r_52_0;
  reg  [63:0]      r_52_1;
  reg  [63:0]      r_53_0;
  reg  [63:0]      r_53_1;
  reg  [63:0]      r_54_0;
  reg  [63:0]      r_54_1;
  reg  [63:0]      r_55_0;
  reg  [63:0]      r_55_1;
  reg  [63:0]      r_56_0;
  reg  [63:0]      r_56_1;
  reg  [63:0]      r_57_0;
  reg  [63:0]      r_57_1;
  reg  [63:0]      r_58_0;
  reg  [63:0]      r_58_1;
  reg  [63:0]      r_59_0;
  reg  [63:0]      r_59_1;
  reg  [63:0]      r_60_0;
  reg  [63:0]      r_60_1;
  reg  [63:0]      r_61_0;
  reg  [63:0]      r_61_1;
  reg  [63:0]      r_62_0;
  reg  [63:0]      r_62_1;
  reg  [63:0]      r_63_0;
  reg  [63:0]      r_63_1;
  reg  [63:0]      r_64_0;
  reg  [63:0]      r_64_1;
  reg  [63:0]      r_65_0;
  reg  [63:0]      r_65_1;
  reg  [63:0]      r_66_0;
  reg  [63:0]      r_66_1;
  reg  [63:0]      r_67_0;
  reg  [63:0]      r_67_1;
  reg  [63:0]      r_68_0;
  reg  [63:0]      r_68_1;
  reg  [63:0]      r_69_0;
  reg  [63:0]      r_69_1;
  reg  [63:0]      r_70_0;
  reg  [63:0]      r_70_1;
  reg  [63:0]      r_71_0;
  reg  [63:0]      r_71_1;
  reg  [63:0]      r_72_0;
  reg  [63:0]      r_72_1;
  reg  [63:0]      r_73_0;
  reg  [63:0]      r_73_1;
  reg  [63:0]      r_74_0;
  reg  [63:0]      r_74_1;
  reg  [63:0]      r_75_0;
  reg  [63:0]      r_75_1;
  reg  [63:0]      r_76_0;
  reg  [63:0]      r_76_1;
  reg  [63:0]      r_77_0;
  reg  [63:0]      r_77_1;
  reg  [63:0]      r_78_0;
  reg  [63:0]      r_78_1;
  reg  [63:0]      r_79_0;
  reg  [63:0]      r_79_1;
  reg  [63:0]      r_80_0;
  reg  [63:0]      r_80_1;
  reg  [63:0]      r_81_0;
  reg  [63:0]      r_81_1;
  reg  [63:0]      r_82_0;
  reg  [63:0]      r_82_1;
  reg  [63:0]      r_83_0;
  reg  [63:0]      r_83_1;
  reg  [63:0]      r_84_0;
  reg  [63:0]      r_84_1;
  reg  [63:0]      r_85_0;
  reg  [63:0]      r_85_1;
  reg  [63:0]      r_86_0;
  reg  [63:0]      r_86_1;
  reg  [1:0]       colCountLast;
  reg              colLatched;
  wire [31:0]      _GEN_6 = {29'h0, colCountLast, 1'h0};
  always @(posedge clock) begin
    if (reset) begin
      vk_reg_0 <= 64'h0;
      vk_reg_1 <= 64'h0;
      vk_reg_2 <= 64'h0;
      vk_reg_3 <= 64'h0;
      tk_reg <= 32'h0;
      counter <= 32'h0;
      index <= 2'h0;
      index_2 <= 2'h0;
      scalar_reg <= 64'h0;
      index2 <= 2'h0;
      colCountLast <= 2'h0;
      colLatched <= 1'h0;
    end
    else begin
      automatic logic _GEN_7;
      automatic logic _GEN_8 = counter > 32'h48;
      automatic logic _GEN_9;
      _GEN_7 = _GEN & _GEN_0;
      _GEN_9 = io_en_in & ~colLatched;
      if (_GEN_7) begin
        automatic logic [1:0] _index_T_1 = index + 2'h1;
        if (_index_T_1 == 2'h0)
          vk_reg_0 <= _vk_io_out_s_1;
        else if (index == 2'h0)
          vk_reg_0 <= _vk_io_out_s_0;
        if (_index_T_1 == 2'h1)
          vk_reg_1 <= _vk_io_out_s_1;
        else if (index == 2'h1)
          vk_reg_1 <= _vk_io_out_s_0;
        if (_index_T_1 == 2'h2)
          vk_reg_2 <= _vk_io_out_s_1;
        else if (index == 2'h2)
          vk_reg_2 <= _vk_io_out_s_0;
        if (&_index_T_1)
          vk_reg_3 <= _vk_io_out_s_1;
        else if (&index)
          vk_reg_3 <= _vk_io_out_s_0;
      end
      if (io_en_in & counter == 32'h0)
        tk_reg <= io_tk_in;
      if (io_counter_reset) begin
        counter <= 32'h0;
        index <= 2'h0;
        index_2 <= 2'h0;
        index2 <= 2'h0;
        colCountLast <= 2'h0;
      end
      else begin
        if (io_en_in)
          counter <= counter + 32'h1;
        if (_GEN_7)
          index <= index - 2'h2;
        if (~_GEN | _GEN_0) begin
        end
        else
          index_2 <= index_2 - 2'h2;
        if (_GEN_5)
          index2 <= index2 - 2'h2;
        if (_GEN_9)
          colCountLast <= io_column_count;
      end
      if (_GEN_8 & counter == 32'h4B | _GEN_8 & counter == 32'h49)
        scalar_reg <= {_mult_0_io_out_s, _mult_1_io_out_s};
      colLatched <= ~io_counter_reset & (_GEN_9 | colLatched);
    end
    r_0 <= io_xk_in_0;
    r_1 <= io_xk_in_1;
    r_1_0 <= r_0;
    r_1_1 <= r_1;
    r_2_0 <= r_1_0;
    r_2_1 <= r_1_1;
    r_3_0 <= r_2_0;
    r_3_1 <= r_2_1;
    r_4_0 <= r_3_0;
    r_4_1 <= r_3_1;
    r_5_0 <= r_4_0;
    r_5_1 <= r_4_1;
    r_6_0 <= r_5_0;
    r_6_1 <= r_5_1;
    r_7_0 <= r_6_0;
    r_7_1 <= r_6_1;
    r_8_0 <= r_7_0;
    r_8_1 <= r_7_1;
    r_9_0 <= r_8_0;
    r_9_1 <= r_8_1;
    r_10_0 <= r_9_0;
    r_10_1 <= r_9_1;
    r_11_0 <= r_10_0;
    r_11_1 <= r_10_1;
    r_12_0 <= r_11_0;
    r_12_1 <= r_11_1;
    r_13_0 <= io_xk_in_0;
    r_13_1 <= io_xk_in_1;
    r_14_0 <= r_13_0;
    r_14_1 <= r_13_1;
    r_15_0 <= r_14_0;
    r_15_1 <= r_14_1;
    r_16_0 <= r_15_0;
    r_16_1 <= r_15_1;
    r_17_0 <= r_16_0;
    r_17_1 <= r_16_1;
    r_18_0 <= r_17_0;
    r_18_1 <= r_17_1;
    r_19_0 <= r_18_0;
    r_19_1 <= r_18_1;
    r_20_0 <= r_19_0;
    r_20_1 <= r_19_1;
    r_21_0 <= r_20_0;
    r_21_1 <= r_20_1;
    r_22_0 <= r_21_0;
    r_22_1 <= r_21_1;
    r_23_0 <= r_22_0;
    r_23_1 <= r_22_1;
    r_24_0 <= r_23_0;
    r_24_1 <= r_23_1;
    r_25_0 <= r_24_0;
    r_25_1 <= r_24_1;
    r_26_0 <= r_25_0;
    r_26_1 <= r_25_1;
    r_27_0 <= r_26_0;
    r_27_1 <= r_26_1;
    r_28_0 <= r_27_0;
    r_28_1 <= r_27_1;
    r_29_0 <= r_28_0;
    r_29_1 <= r_28_1;
    r_30_0 <= r_29_0;
    r_30_1 <= r_29_1;
    r_31_0 <= r_30_0;
    r_31_1 <= r_30_1;
    r_32_0 <= r_31_0;
    r_32_1 <= r_31_1;
    r_33_0 <= r_32_0;
    r_33_1 <= r_32_1;
    r_34_0 <= r_33_0;
    r_34_1 <= r_33_1;
    r_35_0 <= r_34_0;
    r_35_1 <= r_34_1;
    r_36_0 <= r_35_0;
    r_36_1 <= r_35_1;
    r_37_0 <= r_36_0;
    r_37_1 <= r_36_1;
    r_38_0 <= r_37_0;
    r_38_1 <= r_37_1;
    r_39_0 <= r_38_0;
    r_39_1 <= r_38_1;
    r_40_0 <= r_39_0;
    r_40_1 <= r_39_1;
    r_41_0 <= r_40_0;
    r_41_1 <= r_40_1;
    r_42_0 <= r_41_0;
    r_42_1 <= r_41_1;
    r_43_0 <= r_42_0;
    r_43_1 <= r_42_1;
    r_44_0 <= r_43_0;
    r_44_1 <= r_43_1;
    r_45_0 <= r_44_0;
    r_45_1 <= r_44_1;
    r_46_0 <= r_45_0;
    r_46_1 <= r_45_1;
    r_47_0 <= r_46_0;
    r_47_1 <= r_46_1;
    r_48_0 <= r_47_0;
    r_48_1 <= r_47_1;
    r_49_0 <= r_48_0;
    r_49_1 <= r_48_1;
    r_50_0 <= r_49_0;
    r_50_1 <= r_49_1;
    r_51_0 <= r_50_0;
    r_51_1 <= r_50_1;
    r_52_0 <= r_51_0;
    r_52_1 <= r_51_1;
    r_53_0 <= r_52_0;
    r_53_1 <= r_52_1;
    r_54_0 <= r_53_0;
    r_54_1 <= r_53_1;
    r_55_0 <= r_54_0;
    r_55_1 <= r_54_1;
    r_56_0 <= r_55_0;
    r_56_1 <= r_55_1;
    r_57_0 <= r_56_0;
    r_57_1 <= r_56_1;
    r_58_0 <= r_57_0;
    r_58_1 <= r_57_1;
    r_59_0 <= r_58_0;
    r_59_1 <= r_58_1;
    r_60_0 <= r_59_0;
    r_60_1 <= r_59_1;
    r_61_0 <= r_60_0;
    r_61_1 <= r_60_1;
    r_62_0 <= r_61_0;
    r_62_1 <= r_61_1;
    r_63_0 <= r_62_0;
    r_63_1 <= r_62_1;
    r_64_0 <= r_63_0;
    r_64_1 <= r_63_1;
    r_65_0 <= r_64_0;
    r_65_1 <= r_64_1;
    r_66_0 <= r_65_0;
    r_66_1 <= r_65_1;
    r_67_0 <= r_66_0;
    r_67_1 <= r_66_1;
    r_68_0 <= r_67_0;
    r_68_1 <= r_67_1;
    r_69_0 <= r_68_0;
    r_69_1 <= r_68_1;
    r_70_0 <= r_69_0;
    r_70_1 <= r_69_1;
    r_71_0 <= r_70_0;
    r_71_1 <= r_70_1;
    r_72_0 <= r_71_0;
    r_72_1 <= r_71_1;
    r_73_0 <= r_72_0;
    r_73_1 <= r_72_1;
    r_74_0 <= r_73_0;
    r_74_1 <= r_73_1;
    r_75_0 <= r_74_0;
    r_75_1 <= r_74_1;
    r_76_0 <= r_75_0;
    r_76_1 <= r_75_1;
    r_77_0 <= r_76_0;
    r_77_1 <= r_76_1;
    r_78_0 <= r_77_0;
    r_78_1 <= r_77_1;
    r_79_0 <= r_78_0;
    r_79_1 <= r_78_1;
    r_80_0 <= r_79_0;
    r_80_1 <= r_79_1;
    r_81_0 <= r_80_0;
    r_81_1 <= r_80_1;
    r_82_0 <= r_81_0;
    r_82_1 <= r_81_1;
    r_83_0 <= r_82_0;
    r_83_1 <= r_82_1;
    r_84_0 <= r_83_0;
    r_84_1 <= r_83_1;
    r_85_0 <= r_84_0;
    r_85_1 <= r_84_1;
    r_86_0 <= r_85_0;
    r_86_1 <= r_85_1;
  end // always @(posedge)
  vk_gen vk (
    .clock            (clock),
    .reset            (reset),
    .io_xk_in_0       (io_en_in ? io_xk_in_0 : 64'h0),
    .io_xk_in_1       (io_en_in ? io_xk_in_1 : 64'h0),
    .io_alpha_in      (io_en_in ? io_alpha_in : 64'h0),
    .io_in_en         (io_en_in),
    .io_counter_reset (io_en_in & io_counter_reset),
    .io_out_s_0       (_vk_io_out_s_0),
    .io_out_s_1       (_vk_io_out_s_1)
  );
  cmplx_dot_iterative dot (
    .clock            (clock),
    .reset            (reset),
    .io_vec_a_0       (_GEN ? (_GEN_0 ? _vk_io_out_s_0 : _GEN_1[index_2]) : 64'h0),
    .io_vec_a_1       (_GEN ? (_GEN_0 ? _vk_io_out_s_1 : _GEN_1[index_2 + 2'h1]) : 64'h0),
    .io_vec_b_0       (_GEN ? r_12_0 : 64'h0),
    .io_vec_b_1       (_GEN ? r_12_1 : 64'h0),
    .io_counter_reset (_GEN & io_counter_reset),
    .io_in_en         (_GEN),
    .io_out_real      (_dot_io_out_real),
    .io_out_imag      (_dot_io_out_imag)
  );
  FP_mult_32_10_v2 mult_0 (
    .clock    (clock),
    .io_in_en (_GEN_3),
    .io_in_a  (_GEN_4),
    .io_in_b  (_GEN_2 ? _dot_io_out_real : 32'h0),
    .io_out_s (_mult_0_io_out_s)
  );
  FP_mult_32_10_v2 mult_1 (
    .clock    (clock),
    .io_in_en (_GEN_3),
    .io_in_a  (_GEN_4),
    .io_in_b  (_GEN_2 ? _dot_io_out_imag : 32'h0),
    .io_out_s (_mult_1_io_out_s)
  );
  iterative_axpy axpy (
    .clock      (clock),
    .reset      (reset),
    .io_s_in    (_GEN_5 ? scalar_reg : 64'h0),
    .io_vk_in_0 (_GEN_5 ? _GEN_1[index2] : 64'h0),
    .io_vk_in_1 (_GEN_5 ? _GEN_1[index2 + 2'h1] : 64'h0),
    .io_xk_in_0 (_GEN_5 ? r_86_0 : 64'h0),
    .io_xk_in_1 (_GEN_5 ? r_86_1 : 64'h0),
    .io_en_in   (_GEN_5),
    .io_out_s_0 (io_out_s_0),
    .io_out_s_1 (io_out_s_1)
  );
  assign io_valid_out = counter > 32'h6D & counter < _GEN_6 + 32'h6E;
  assign io_col2_done = colCountLast[1] & counter == 32'h71;
  assign io_updates_done = counter == _GEN_6 + 32'h6D;
endmodule

