// Generated by CIRCT firtool-1.62.0
module full_adder(
  input  [7:0] io_in_a,
               io_in_b,
  output [7:0] io_out_s,
  output       io_out_c
);

  wire [8:0] result = {1'h0, io_in_a} + {1'h0, io_in_b};
  assign io_out_s = result[7:0];
  assign io_out_c = result[8];
endmodule

module multiplier(
  input  [23:0] io_in_a,
                io_in_b,
  output [47:0] io_out_s
);

  assign io_out_s = {24'h0, io_in_a} * {24'h0, io_in_b};
endmodule

module FP_mult_32_10_v2(
  input         clock,
                io_in_en,
  input  [31:0] io_in_a,
                io_in_b,
  output [31:0] io_out_s
);

  wire [47:0] _multiplier_io_out_s;
  wire [7:0]  _exp_adder_io_out_s;
  wire        _exp_adder_io_out_c;
  reg  [31:0] in_a;
  reg  [31:0] in_b;
  reg  [23:0] whole_frac_sr_0;
  reg  [23:0] whole_frac_sr_1;
  reg         sign_sr_0;
  reg         sign_sr_1;
  reg  [7:0]  exp_sr_0;
  reg  [7:0]  exp_sr_1;
  reg         new_sign_sr;
  reg  [7:0]  exp_sr_2_0;
  reg  [7:0]  exp_sr_2_1;
  reg  [23:0] whole_frac_sr_2_0;
  reg  [23:0] whole_frac_sr_2_1;
  reg  [7:0]  exp_adder_outs_sr;
  reg         exp_adder_outc_sr;
  reg         new_sign_sr_2;
  reg  [7:0]  exp_sr_3_1;
  reg  [23:0] whole_frac_sr_3_0;
  reg  [23:0] whole_frac_sr_3_1;
  reg  [47:0] frac_mult_out_sr;
  reg  [7:0]  exp_adder_outs_sr_2;
  reg         exp_adder_outc_sr_2;
  reg         new_sign_sr_3;
  reg  [7:0]  exp_sr_4_1;
  reg  [7:0]  uo_check_r;
  reg         carry_flag;
  reg  [7:0]  exp_sum;
  reg         new_sign_reg;
  reg         msb_check;
  reg  [47:0] new_frac_reg;
  reg         u_flag_reg;
  reg         o_flag_reg;
  reg  [7:0]  new_exp_reg;
  reg         new_sign_reg_2;
  reg  [47:0] new_frac_reg_2;
  reg  [7:0]  out_exp_innermux;
  reg  [22:0] out_frac_innermux;
  reg         u_flag_reg_2;
  reg         o_flag_reg_2;
  reg         new_sign_reg_3;
  reg  [7:0]  out_exp_innermux_2;
  reg  [22:0] out_frac_innermux_2;
  reg         new_sign_reg_4;
  reg         u_flag_reg_3;
  reg  [31:0] io_out_s_r;
  always @(posedge clock) begin
    if (io_in_en) begin
      automatic logic       uo_check = uo_check_r < 8'h7F;
      automatic logic [8:0] _o_flag_reg_T_1 = {1'h0, exp_sum} + {8'h0, msb_check};
      in_a <= io_in_a;
      in_b <= io_in_b;
      whole_frac_sr_0 <= {1'h1, in_a[22:0]};
      whole_frac_sr_1 <= {1'h1, in_b[22:0]};
      sign_sr_0 <= in_a[31];
      sign_sr_1 <= in_b[31];
      exp_sr_0 <= (&(in_a[30:23])) ? 8'hFE : in_a[30:23] == 8'h0 ? 8'h1 : in_a[30:23];
      exp_sr_1 <= (&(in_b[30:23])) ? 8'hFE : in_b[30:23] == 8'h0 ? 8'h1 : in_b[30:23];
      new_sign_sr <= sign_sr_0 ^ sign_sr_1;
      exp_sr_2_0 <= exp_sr_0;
      exp_sr_2_1 <= exp_sr_1;
      whole_frac_sr_2_0 <= whole_frac_sr_0;
      whole_frac_sr_2_1 <= whole_frac_sr_1;
      exp_adder_outs_sr <= _exp_adder_io_out_s;
      exp_adder_outc_sr <= _exp_adder_io_out_c;
      new_sign_sr_2 <= new_sign_sr;
      exp_sr_3_1 <= exp_sr_2_1;
      whole_frac_sr_3_0 <= whole_frac_sr_2_0;
      whole_frac_sr_3_1 <= whole_frac_sr_2_1;
      frac_mult_out_sr <= _multiplier_io_out_s;
      exp_adder_outs_sr_2 <= exp_adder_outs_sr;
      exp_adder_outc_sr_2 <= exp_adder_outc_sr;
      new_sign_sr_3 <= new_sign_sr_2;
      exp_sr_4_1 <= exp_sr_3_1;
      uo_check_r <= exp_sr_4_1;
      carry_flag <= exp_adder_outc_sr_2;
      exp_sum <= exp_adder_outs_sr_2;
      new_sign_reg <= new_sign_sr_3;
      msb_check <= frac_mult_out_sr[47];
      new_frac_reg <= frac_mult_out_sr;
      u_flag_reg <= uo_check & (~carry_flag | _o_flag_reg_T_1 == 9'h0);
      o_flag_reg <= ~uo_check & (carry_flag | _o_flag_reg_T_1 > 9'hFE);
      new_exp_reg <= exp_sum;
      new_sign_reg_2 <= new_sign_reg;
      new_frac_reg_2 <= new_frac_reg;
      out_exp_innermux <= new_frac_reg_2[47] ? new_exp_reg + 8'h1 : new_exp_reg;
      out_frac_innermux <=
        new_frac_reg_2[47] ? new_frac_reg_2[46:24] : new_frac_reg_2[45:23];
      u_flag_reg_2 <= u_flag_reg;
      o_flag_reg_2 <= o_flag_reg;
      new_sign_reg_3 <= new_sign_reg_2;
      out_exp_innermux_2 <= o_flag_reg_2 ? 8'hFE : out_exp_innermux;
      out_frac_innermux_2 <= o_flag_reg_2 ? 23'h7FFFFF : out_frac_innermux;
      new_sign_reg_4 <= new_sign_reg_3;
      u_flag_reg_3 <= u_flag_reg_2;
      io_out_s_r <=
        {new_sign_reg_4,
         u_flag_reg_3 ? 8'h1 : out_exp_innermux_2,
         u_flag_reg_3 ? 23'h0 : out_frac_innermux_2};
    end
  end // always @(posedge)
  full_adder exp_adder (
    .io_in_a  (exp_sr_2_0),
    .io_in_b  (exp_sr_2_1 - 8'h7F),
    .io_out_s (_exp_adder_io_out_s),
    .io_out_c (_exp_adder_io_out_c)
  );
  multiplier multiplier (
    .io_in_a  (whole_frac_sr_3_0),
    .io_in_b  (whole_frac_sr_3_1),
    .io_out_s (_multiplier_io_out_s)
  );
  assign io_out_s = io_out_s_r;
endmodule

module full_subtractor(
  input  [7:0] io_in_a,
               io_in_b,
  output [7:0] io_out_s,
  output       io_out_c
);

  wire [8:0] result = {1'h0, io_in_a} - {1'h0, io_in_b};
  assign io_out_s = result[7:0];
  assign io_out_c = result[8];
endmodule

module full_adder_4(
  input  [23:0] io_in_a,
                io_in_b,
  output [23:0] io_out_s,
  output        io_out_c
);

  wire [24:0] result = {1'h0, io_in_a} + {1'h0, io_in_b};
  assign io_out_s = result[23:0];
  assign io_out_c = result[24];
endmodule

module LZC_enc2(
  input  [1:0] io_in_r,
  output [1:0] io_out_e
);

  assign io_out_e = io_in_r == 2'h0 ? 2'h2 : {1'h0, io_in_r == 2'h1};
endmodule

module LZC_Merge2(
  input  [1:0] io_in_h,
               io_in_l,
  output [2:0] io_out_m
);

  assign io_out_m =
    {io_in_h[1] & io_in_l[1],
     io_in_h[1] ? ~(io_in_l[1]) : io_in_h[1],
     io_in_h[1] ? io_in_l[0] : io_in_h[0]};
endmodule

module LZC_Merge3(
  input  [2:0] io_in_h,
               io_in_l,
  output [3:0] io_out_m
);

  assign io_out_m =
    {io_in_h[2] & io_in_l[2],
     io_in_h[2] ? ~(io_in_l[2]) : io_in_h[2],
     io_in_h[2] ? io_in_l[1:0] : io_in_h[1:0]};
endmodule

module LZC_Merge4(
  input  [3:0] io_in_h,
               io_in_l,
  output [4:0] io_out_m
);

  assign io_out_m =
    {io_in_h[3] & io_in_l[3],
     io_in_h[3] ? ~(io_in_l[3]) : io_in_h[3],
     io_in_h[3] ? io_in_l[2:0] : io_in_h[2:0]};
endmodule

module LZC_Merge5(
  input  [4:0] io_in_h,
               io_in_l,
  output [5:0] io_out_m
);

  assign io_out_m =
    {io_in_h[4] & io_in_l[4],
     io_in_h[4] ? ~(io_in_l[4]) : io_in_h[4],
     io_in_h[4] ? io_in_l[3:0] : io_in_h[3:0]};
endmodule

module LZC32_2(
  input  [31:0] io_in_d,
  output [5:0]  io_out_c
);

  wire [4:0] _LZC_Merge4_1_io_out_m;
  wire [4:0] _LZC_Merge4_io_out_m;
  wire [3:0] _LZC_Merge3_3_io_out_m;
  wire [3:0] _LZC_Merge3_2_io_out_m;
  wire [3:0] _LZC_Merge3_1_io_out_m;
  wire [3:0] _LZC_Merge3_io_out_m;
  wire [2:0] _LZC_Merge2_7_io_out_m;
  wire [2:0] _LZC_Merge2_6_io_out_m;
  wire [2:0] _LZC_Merge2_5_io_out_m;
  wire [2:0] _LZC_Merge2_4_io_out_m;
  wire [2:0] _LZC_Merge2_3_io_out_m;
  wire [2:0] _LZC_Merge2_2_io_out_m;
  wire [2:0] _LZC_Merge2_1_io_out_m;
  wire [2:0] _LZC_Merge2_io_out_m;
  wire [1:0] _LZC_enc2_15_io_out_e;
  wire [1:0] _LZC_enc2_14_io_out_e;
  wire [1:0] _LZC_enc2_13_io_out_e;
  wire [1:0] _LZC_enc2_12_io_out_e;
  wire [1:0] _LZC_enc2_11_io_out_e;
  wire [1:0] _LZC_enc2_10_io_out_e;
  wire [1:0] _LZC_enc2_9_io_out_e;
  wire [1:0] _LZC_enc2_8_io_out_e;
  wire [1:0] _LZC_enc2_7_io_out_e;
  wire [1:0] _LZC_enc2_6_io_out_e;
  wire [1:0] _LZC_enc2_5_io_out_e;
  wire [1:0] _LZC_enc2_4_io_out_e;
  wire [1:0] _LZC_enc2_3_io_out_e;
  wire [1:0] _LZC_enc2_2_io_out_e;
  wire [1:0] _LZC_enc2_1_io_out_e;
  wire [1:0] _LZC_enc2_io_out_e;
  LZC_enc2 LZC_enc2 (
    .io_in_r  (io_in_d[1:0]),
    .io_out_e (_LZC_enc2_io_out_e)
  );
  LZC_enc2 LZC_enc2_1 (
    .io_in_r  (io_in_d[3:2]),
    .io_out_e (_LZC_enc2_1_io_out_e)
  );
  LZC_enc2 LZC_enc2_2 (
    .io_in_r  (io_in_d[5:4]),
    .io_out_e (_LZC_enc2_2_io_out_e)
  );
  LZC_enc2 LZC_enc2_3 (
    .io_in_r  (io_in_d[7:6]),
    .io_out_e (_LZC_enc2_3_io_out_e)
  );
  LZC_enc2 LZC_enc2_4 (
    .io_in_r  (io_in_d[9:8]),
    .io_out_e (_LZC_enc2_4_io_out_e)
  );
  LZC_enc2 LZC_enc2_5 (
    .io_in_r  (io_in_d[11:10]),
    .io_out_e (_LZC_enc2_5_io_out_e)
  );
  LZC_enc2 LZC_enc2_6 (
    .io_in_r  (io_in_d[13:12]),
    .io_out_e (_LZC_enc2_6_io_out_e)
  );
  LZC_enc2 LZC_enc2_7 (
    .io_in_r  (io_in_d[15:14]),
    .io_out_e (_LZC_enc2_7_io_out_e)
  );
  LZC_enc2 LZC_enc2_8 (
    .io_in_r  (io_in_d[17:16]),
    .io_out_e (_LZC_enc2_8_io_out_e)
  );
  LZC_enc2 LZC_enc2_9 (
    .io_in_r  (io_in_d[19:18]),
    .io_out_e (_LZC_enc2_9_io_out_e)
  );
  LZC_enc2 LZC_enc2_10 (
    .io_in_r  (io_in_d[21:20]),
    .io_out_e (_LZC_enc2_10_io_out_e)
  );
  LZC_enc2 LZC_enc2_11 (
    .io_in_r  (io_in_d[23:22]),
    .io_out_e (_LZC_enc2_11_io_out_e)
  );
  LZC_enc2 LZC_enc2_12 (
    .io_in_r  (io_in_d[25:24]),
    .io_out_e (_LZC_enc2_12_io_out_e)
  );
  LZC_enc2 LZC_enc2_13 (
    .io_in_r  (io_in_d[27:26]),
    .io_out_e (_LZC_enc2_13_io_out_e)
  );
  LZC_enc2 LZC_enc2_14 (
    .io_in_r  (io_in_d[29:28]),
    .io_out_e (_LZC_enc2_14_io_out_e)
  );
  LZC_enc2 LZC_enc2_15 (
    .io_in_r  (io_in_d[31:30]),
    .io_out_e (_LZC_enc2_15_io_out_e)
  );
  LZC_Merge2 LZC_Merge2 (
    .io_in_h  (_LZC_enc2_15_io_out_e),
    .io_in_l  (_LZC_enc2_14_io_out_e),
    .io_out_m (_LZC_Merge2_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_1 (
    .io_in_h  (_LZC_enc2_13_io_out_e),
    .io_in_l  (_LZC_enc2_12_io_out_e),
    .io_out_m (_LZC_Merge2_1_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_2 (
    .io_in_h  (_LZC_enc2_11_io_out_e),
    .io_in_l  (_LZC_enc2_10_io_out_e),
    .io_out_m (_LZC_Merge2_2_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_3 (
    .io_in_h  (_LZC_enc2_9_io_out_e),
    .io_in_l  (_LZC_enc2_8_io_out_e),
    .io_out_m (_LZC_Merge2_3_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_4 (
    .io_in_h  (_LZC_enc2_7_io_out_e),
    .io_in_l  (_LZC_enc2_6_io_out_e),
    .io_out_m (_LZC_Merge2_4_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_5 (
    .io_in_h  (_LZC_enc2_5_io_out_e),
    .io_in_l  (_LZC_enc2_4_io_out_e),
    .io_out_m (_LZC_Merge2_5_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_6 (
    .io_in_h  (_LZC_enc2_3_io_out_e),
    .io_in_l  (_LZC_enc2_2_io_out_e),
    .io_out_m (_LZC_Merge2_6_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_7 (
    .io_in_h  (_LZC_enc2_1_io_out_e),
    .io_in_l  (_LZC_enc2_io_out_e),
    .io_out_m (_LZC_Merge2_7_io_out_m)
  );
  LZC_Merge3 LZC_Merge3 (
    .io_in_h  (_LZC_Merge2_io_out_m),
    .io_in_l  (_LZC_Merge2_1_io_out_m),
    .io_out_m (_LZC_Merge3_io_out_m)
  );
  LZC_Merge3 LZC_Merge3_1 (
    .io_in_h  (_LZC_Merge2_2_io_out_m),
    .io_in_l  (_LZC_Merge2_3_io_out_m),
    .io_out_m (_LZC_Merge3_1_io_out_m)
  );
  LZC_Merge3 LZC_Merge3_2 (
    .io_in_h  (_LZC_Merge2_4_io_out_m),
    .io_in_l  (_LZC_Merge2_5_io_out_m),
    .io_out_m (_LZC_Merge3_2_io_out_m)
  );
  LZC_Merge3 LZC_Merge3_3 (
    .io_in_h  (_LZC_Merge2_6_io_out_m),
    .io_in_l  (_LZC_Merge2_7_io_out_m),
    .io_out_m (_LZC_Merge3_3_io_out_m)
  );
  LZC_Merge4 LZC_Merge4 (
    .io_in_h  (_LZC_Merge3_io_out_m),
    .io_in_l  (_LZC_Merge3_1_io_out_m),
    .io_out_m (_LZC_Merge4_io_out_m)
  );
  LZC_Merge4 LZC_Merge4_1 (
    .io_in_h  (_LZC_Merge3_2_io_out_m),
    .io_in_l  (_LZC_Merge3_3_io_out_m),
    .io_out_m (_LZC_Merge4_1_io_out_m)
  );
  LZC_Merge5 LZC_Merge5 (
    .io_in_h  (_LZC_Merge4_io_out_m),
    .io_in_l  (_LZC_Merge4_1_io_out_m),
    .io_out_m (io_out_c)
  );
endmodule

module FP_add_32_13(
  input         clock,
                io_in_en,
  input  [31:0] io_in_a,
                io_in_b,
  output [31:0] io_out_s
);

  wire [5:0]  _LZC32_2_io_out_c;
  wire [23:0] _full_adder_io_out_s;
  wire        _full_adder_io_out_c;
  wire [7:0]  _exp_subtractor_io_out_s;
  wire        _exp_subtractor_io_out_c;
  reg  [31:0] in_a;
  reg  [31:0] in_b;
  reg  [7:0]  exp_sr_0;
  reg  [7:0]  exp_sr_1;
  reg  [23:0] whole_frac_sr_0;
  reg  [23:0] whole_frac_sr_1;
  reg         sign_sr_0;
  reg         sign_sr_1;
  reg         exp_sub_out_c_r;
  reg         exp_sub_out_c;
  reg  [7:0]  exp_sub_out_s_r;
  reg  [7:0]  exp_sub_out_s;
  reg  [7:0]  exp_sr_2_r_0;
  reg  [7:0]  exp_sr_2_r_1;
  reg  [7:0]  exp_sr_2_0;
  reg  [7:0]  exp_sr_2_1;
  reg  [23:0] whole_frac_sr_2_r_0;
  reg  [23:0] whole_frac_sr_2_r_1;
  reg  [23:0] whole_frac_sr_2_0;
  reg  [23:0] whole_frac_sr_2_1;
  reg         sign_sr_2_r_0;
  reg         sign_sr_2_r_1;
  reg         sign_sr_2_0;
  reg         sign_sr_2_1;
  reg         eqexp_arrange;
  reg  [7:0]  exp_sr_3_0;
  reg  [7:0]  exp_sr_3_1;
  reg  [23:0] whole_frac_sr_3_0;
  reg  [23:0] whole_frac_sr_3_1;
  reg         sign_sr_3_0;
  reg         sign_sr_3_1;
  reg         exp_sub_out_c_2;
  reg  [7:0]  exp_sub_out_s_2;
  reg         redundant_op;
  reg  [23:0] fracadd_in_a;
  reg  [23:0] fracadd_in_b;
  reg  [7:0]  ref_exp;
  reg         ref_sign;
  reg         diff_sign;
  reg         frac_adder_out_c_r;
  reg         frac_adder_out_c;
  reg  [23:0] frac_adder_out_s_r;
  reg  [23:0] frac_adder_out_s;
  reg         diff_sign_2_r;
  reg         diff_sign_2;
  reg         redundant_op_2_r;
  reg         redundant_op_2;
  reg         ref_sign_2_r;
  reg         ref_sign_2;
  reg  [7:0]  ref_exp_2_r;
  reg  [7:0]  ref_exp_2;
  reg         sign_out;
  reg  [23:0] fracadd_outs;
  reg         fracadd_outc;
  reg         diff_sign_3;
  reg  [7:0]  ref_exp_3;
  reg  [5:0]  leadzeroindex;
  reg  [7:0]  ref_exp_4;
  reg  [23:0] fracadd_outs_2;
  reg         diff_sign_4;
  reg         fracadd_outc_2;
  reg         sign_out_2;
  reg         diff_sign_5;
  reg  [85:0] innermux_frac_true;
  reg  [22:0] innermux_frac_false;
  reg  [7:0]  innermux_exp_true;
  reg  [7:0]  innermux_exp_false;
  reg         sign_out_3;
  reg  [85:0] norm_out_frac_r;
  reg  [85:0] norm_out_frac_r_1;
  reg  [7:0]  norm_out_exp_r;
  reg  [7:0]  norm_out_exp;
  reg         norm_out_sign_r;
  reg         norm_out_sign;
  always @(posedge clock) begin
    if (io_in_en) begin
      automatic logic        _GEN = exp_sub_out_c_2 | eqexp_arrange;
      automatic logic [8:0]  _GEN_0 = {1'h0, ref_exp_4};
      automatic logic [8:0]  red = _GEN_0 - {3'h0, leadzeroindex};
      automatic logic [8:0]  inc = _GEN_0 + 9'h1;
      automatic logic [85:0] _GEN_1 = {63'h0, fracadd_outs_2[22:0]};
      automatic logic        _innermux_exp_true_T_2 = red == 9'h0;
      automatic logic        _innermux_exp_false_T_2 = inc > 9'hFE;
      in_a <= io_in_a;
      in_b <= io_in_b;
      exp_sr_0 <=
        {1'h0, in_a[30:23]} > 9'hFE ? 8'hFE : in_a[30:23] == 8'h0 ? 8'h1 : in_a[30:23];
      exp_sr_1 <=
        {1'h0, in_b[30:23]} > 9'hFE ? 8'hFE : in_b[30:23] == 8'h0 ? 8'h1 : in_b[30:23];
      whole_frac_sr_0 <= {1'h1, in_a[22:0]};
      whole_frac_sr_1 <= {1'h1, in_b[22:0]};
      sign_sr_0 <= in_a[31];
      sign_sr_1 <= in_b[31];
      exp_sub_out_c_r <= _exp_subtractor_io_out_c;
      exp_sub_out_c <= exp_sub_out_c_r;
      exp_sub_out_s_r <= _exp_subtractor_io_out_s;
      exp_sub_out_s <= exp_sub_out_s_r;
      exp_sr_2_r_0 <= exp_sr_0;
      exp_sr_2_r_1 <= exp_sr_1;
      exp_sr_2_0 <= exp_sr_2_r_0;
      exp_sr_2_1 <= exp_sr_2_r_1;
      whole_frac_sr_2_r_0 <= whole_frac_sr_0;
      whole_frac_sr_2_r_1 <= whole_frac_sr_1;
      whole_frac_sr_2_0 <= whole_frac_sr_2_r_0;
      whole_frac_sr_2_1 <= whole_frac_sr_2_r_1;
      sign_sr_2_r_0 <= sign_sr_0;
      sign_sr_2_r_1 <= sign_sr_1;
      sign_sr_2_0 <= sign_sr_2_r_0;
      sign_sr_2_1 <= sign_sr_2_r_1;
      eqexp_arrange <= exp_sr_2_0 == exp_sr_2_1 & whole_frac_sr_2_1 > whole_frac_sr_2_0;
      exp_sr_3_0 <= exp_sr_2_0;
      exp_sr_3_1 <= exp_sr_2_1;
      whole_frac_sr_3_0 <= whole_frac_sr_2_0;
      whole_frac_sr_3_1 <= whole_frac_sr_2_1;
      sign_sr_3_0 <= sign_sr_2_0;
      sign_sr_3_1 <= sign_sr_2_1;
      exp_sub_out_c_2 <= exp_sub_out_c;
      exp_sub_out_s_2 <= exp_sub_out_s;
      redundant_op <=
        (exp_sub_out_c_2 ? ~exp_sub_out_s_2 + 8'h1 : exp_sub_out_s_2) > 8'h17;
      fracadd_in_a <= _GEN ? whole_frac_sr_3_1 : whole_frac_sr_3_0;
      fracadd_in_b <=
        exp_sub_out_c_2
          ? whole_frac_sr_3_0 >> ~exp_sub_out_s_2 + 8'h1
          : (eqexp_arrange ? whole_frac_sr_3_0 : whole_frac_sr_3_1) >> exp_sub_out_s_2;
      ref_exp <= exp_sub_out_c_2 ? exp_sr_3_1 : exp_sr_3_0;
      ref_sign <= _GEN ? sign_sr_3_1 : sign_sr_3_0;
      diff_sign <= sign_sr_3_0 ^ sign_sr_3_1;
      frac_adder_out_c_r <= _full_adder_io_out_c;
      frac_adder_out_c <= frac_adder_out_c_r;
      frac_adder_out_s_r <= _full_adder_io_out_s;
      frac_adder_out_s <= frac_adder_out_s_r;
      diff_sign_2_r <= diff_sign;
      diff_sign_2 <= diff_sign_2_r;
      redundant_op_2_r <= redundant_op;
      redundant_op_2 <= redundant_op_2_r;
      ref_sign_2_r <= ref_sign;
      ref_sign_2 <= ref_sign_2_r;
      ref_exp_2_r <= ref_exp;
      ref_exp_2 <= ref_exp_2_r;
      sign_out <= diff_sign_2 & ~redundant_op_2 & ~frac_adder_out_c ^ ref_sign_2;
      fracadd_outs <= frac_adder_out_s;
      fracadd_outc <= frac_adder_out_c;
      diff_sign_3 <= diff_sign_2;
      ref_exp_3 <= ref_exp_2;
      leadzeroindex <= _LZC32_2_io_out_c;
      ref_exp_4 <= ref_exp_3;
      fracadd_outs_2 <= fracadd_outs;
      diff_sign_4 <= diff_sign_3;
      fracadd_outc_2 <= fracadd_outc;
      sign_out_2 <= sign_out;
      diff_sign_5 <= diff_sign_4;
      innermux_frac_true <=
        fracadd_outs_2[23]
          ? _GEN_1
          : red[8] | _innermux_exp_true_T_2 ? 86'h0 : _GEN_1 << leadzeroindex;
      innermux_frac_false <=
        fracadd_outc_2
          ? (inc[8] | _innermux_exp_false_T_2 ? 23'h7FFFFF : fracadd_outs_2[23:1])
          : fracadd_outs_2[22:0];
      innermux_exp_true <=
        fracadd_outs_2[23]
          ? ref_exp_4
          : red[8] | _innermux_exp_true_T_2 ? 8'h1 : red[7:0];
      innermux_exp_false <=
        fracadd_outc_2
          ? (inc[8] | _innermux_exp_false_T_2 ? 8'hFE : inc[7:0])
          : ref_exp_4;
      sign_out_3 <= sign_out_2;
      norm_out_frac_r <= diff_sign_5 ? innermux_frac_true : {63'h0, innermux_frac_false};
      norm_out_frac_r_1 <= norm_out_frac_r;
      norm_out_exp_r <= diff_sign_5 ? innermux_exp_true : innermux_exp_false;
      norm_out_exp <= norm_out_exp_r;
      norm_out_sign_r <= sign_out_3;
      norm_out_sign <= norm_out_sign_r;
    end
  end // always @(posedge)
  full_subtractor exp_subtractor (
    .io_in_a  (exp_sr_0),
    .io_in_b  (exp_sr_1),
    .io_out_s (_exp_subtractor_io_out_s),
    .io_out_c (_exp_subtractor_io_out_c)
  );
  full_adder_4 full_adder (
    .io_in_a  (fracadd_in_a),
    .io_in_b  (diff_sign ? ~fracadd_in_b + 24'h1 : fracadd_in_b),
    .io_out_s (_full_adder_io_out_s),
    .io_out_c (_full_adder_io_out_c)
  );
  LZC32_2 LZC32_2 (
    .io_in_d  ({fracadd_outs, 8'hFF}),
    .io_out_c (_LZC32_2_io_out_c)
  );
  assign io_out_s = {norm_out_sign, norm_out_exp, norm_out_frac_r_1[22:0]};
endmodule

module complex_conjugate_mult(
  input         clock,
                reset,
  input  [63:0] io_complexA,
                io_complexB,
  input         io_in_en,
                io_counter_rest,
  output [63:0] io_out_s
);

  wire        _GEN;
  wire [31:0] _FP_adder_Inst_1_io_out_s;
  wire [31:0] _FP_adder_Inst_0_io_out_s;
  wire [31:0] _FP_mult_inst_3_io_out_s;
  wire [31:0] _FP_mult_inst_2_io_out_s;
  wire [31:0] _FP_mult_inst_1_io_out_s;
  wire [31:0] _FP_mult_inst_0_io_out_s;
  reg  [15:0] counter;
  assign _GEN = io_in_en & counter > 16'h9;
  always @(posedge clock) begin
    if (reset)
      counter <= 16'h0;
    else if (io_counter_rest)
      counter <= 16'h0;
    else if (io_in_en)
      counter <= counter + 16'h1;
  end // always @(posedge)
  FP_mult_32_10_v2 FP_mult_inst_0 (
    .clock    (clock),
    .io_in_en (io_in_en),
    .io_in_a  (io_complexA[63:32]),
    .io_in_b  (io_complexB[63:32]),
    .io_out_s (_FP_mult_inst_0_io_out_s)
  );
  FP_mult_32_10_v2 FP_mult_inst_1 (
    .clock    (clock),
    .io_in_en (io_in_en),
    .io_in_a  (io_complexA[31:0]),
    .io_in_b  (io_complexB[31:0]),
    .io_out_s (_FP_mult_inst_1_io_out_s)
  );
  FP_mult_32_10_v2 FP_mult_inst_2 (
    .clock    (clock),
    .io_in_en (io_in_en),
    .io_in_a  (io_complexA[31:0]),
    .io_in_b  (io_complexB[63:32]),
    .io_out_s (_FP_mult_inst_2_io_out_s)
  );
  FP_mult_32_10_v2 FP_mult_inst_3 (
    .clock    (clock),
    .io_in_en (io_in_en),
    .io_in_a  (io_complexA[63:32]),
    .io_in_b  (io_complexB[31:0]),
    .io_out_s (_FP_mult_inst_3_io_out_s)
  );
  FP_add_32_13 FP_adder_Inst_0 (
    .clock    (clock),
    .io_in_en (_GEN),
    .io_in_a  (_GEN ? _FP_mult_inst_0_io_out_s : 32'h0),
    .io_in_b  (_GEN ? _FP_mult_inst_1_io_out_s : 32'h0),
    .io_out_s (_FP_adder_Inst_0_io_out_s)
  );
  FP_add_32_13 FP_adder_Inst_1 (
    .clock    (clock),
    .io_in_en (_GEN),
    .io_in_a  (_GEN ? _FP_mult_inst_2_io_out_s ^ 32'h80000000 : 32'h0),
    .io_in_b  (_GEN ? _FP_mult_inst_3_io_out_s : 32'h0),
    .io_out_s (_FP_adder_Inst_1_io_out_s)
  );
  assign io_out_s = {_FP_adder_Inst_0_io_out_s, _FP_adder_Inst_1_io_out_s};
endmodule

module complex_adder(
  input         clock,
  input  [63:0] io_complexA,
                io_complexB,
  input         io_in_en,
  output [63:0] io_out_s
);

  wire [31:0] _FP_adder_Inst_1_io_out_s;
  wire [31:0] _FP_adder_Inst_0_io_out_s;
  FP_add_32_13 FP_adder_Inst_0 (
    .clock    (clock),
    .io_in_en (io_in_en),
    .io_in_a  (io_complexA[63:32]),
    .io_in_b  (io_complexB[63:32]),
    .io_out_s (_FP_adder_Inst_0_io_out_s)
  );
  FP_add_32_13 FP_adder_Inst_1 (
    .clock    (clock),
    .io_in_en (io_in_en),
    .io_in_a  (io_complexA[31:0]),
    .io_in_b  (io_complexB[31:0]),
    .io_out_s (_FP_adder_Inst_1_io_out_s)
  );
  assign io_out_s = {_FP_adder_Inst_0_io_out_s, _FP_adder_Inst_1_io_out_s};
endmodule

module complex_dot_streaming(
  input         clock,
                reset,
  input  [63:0] io_vec_a_0,
                io_vec_a_1,
                io_vec_b_0,
                io_vec_b_1,
  input         io_in_en,
                io_counter_reset,
  output [63:0] io_out_s
);

  wire [63:0] _adderInst_io_out_s;
  wire [63:0] _MultInst_1_io_out_s;
  wire [63:0] _MultInst_io_out_s;
  complex_conjugate_mult MultInst (
    .clock           (clock),
    .reset           (reset),
    .io_complexA     (io_vec_a_0),
    .io_complexB     (io_vec_b_0),
    .io_in_en        (io_in_en),
    .io_counter_rest (io_counter_reset),
    .io_out_s        (_MultInst_io_out_s)
  );
  complex_conjugate_mult MultInst_1 (
    .clock           (clock),
    .reset           (reset),
    .io_complexA     (io_vec_a_1),
    .io_complexB     (io_vec_b_1),
    .io_in_en        (io_in_en),
    .io_counter_rest (io_counter_reset),
    .io_out_s        (_MultInst_1_io_out_s)
  );
  complex_adder adderInst (
    .clock       (clock),
    .io_complexA (_MultInst_io_out_s),
    .io_complexB (_MultInst_1_io_out_s),
    .io_in_en    (io_in_en),
    .io_out_s    (_adderInst_io_out_s)
  );
  assign io_out_s = io_in_en ? _adderInst_io_out_s : 64'h0;
endmodule

module demux1(
  input  [63:0] io_input,
  input         io_sel,
  output [63:0] io_outputs_0,
                io_outputs_1
);

  assign io_outputs_0 = io_sel ? 64'h0 : io_input;
  assign io_outputs_1 = io_sel ? io_input : 64'h0;
endmodule

module complex_acc(
  input         clock,
                reset,
  input  [63:0] io_input,
  input         io_in_en,
                io_counter_reset,
  output [63:0] io_output
);

  wire [63:0] _demux1_io_outputs_0;
  wire [63:0] _demux1_io_outputs_1;
  reg  [31:0] counter;
  reg         adder_io_in_en_r;
  reg  [63:0] adder_io_complexA_r;
  always @(posedge clock) begin
    if (reset)
      counter <= 32'h0;
    else if (io_counter_reset)
      counter <= 32'h0;
    else if (io_in_en)
      counter <= counter + 32'h1;
    adder_io_in_en_r <= io_in_en;
    adder_io_complexA_r <= _demux1_io_outputs_0;
  end // always @(posedge)
  demux1 demux1 (
    .io_input     (io_input),
    .io_sel       (counter[0]),
    .io_outputs_0 (_demux1_io_outputs_0),
    .io_outputs_1 (_demux1_io_outputs_1)
  );
  complex_adder adder (
    .clock       (clock),
    .io_complexA (adder_io_complexA_r),
    .io_complexB (_demux1_io_outputs_1),
    .io_in_en    (adder_io_in_en_r),
    .io_out_s    (io_output)
  );
endmodule

module cmplx_dot_iterative(
  input         clock,
                reset,
  input  [63:0] io_vec_a_0,
                io_vec_a_1,
                io_vec_b_0,
                io_vec_b_1,
  input         io_counter_reset,
                io_in_en,
  output [31:0] io_out_real
);

  wire [63:0] _d2aInst_0_io_output;
  wire [63:0] _complex_dot_io_out_s;
  reg  [31:0] counter;
  reg         index;
  wire        _GEN = counter > 32'h23;
  always @(posedge clock) begin
    if (reset) begin
      counter <= 32'h0;
      index <= 1'h0;
    end
    else begin
      if (io_counter_reset)
        counter <= 32'h0;
      else if (io_in_en)
        counter <= counter + 32'h1;
      index <= index - 1'h1;
    end
  end // always @(posedge)
  complex_dot_streaming complex_dot (
    .clock            (clock),
    .reset            (reset),
    .io_vec_a_0       (io_vec_a_0),
    .io_vec_a_1       (io_vec_a_1),
    .io_vec_b_0       (io_vec_b_0),
    .io_vec_b_1       (io_vec_b_1),
    .io_in_en         (io_in_en),
    .io_counter_reset (io_counter_reset),
    .io_out_s         (_complex_dot_io_out_s)
  );
  complex_acc d2aInst_0 (
    .clock            (clock),
    .reset            (reset),
    .io_input         (_complex_dot_io_out_s),
    .io_in_en         (_GEN),
    .io_counter_reset (_GEN & io_counter_reset),
    .io_output        (_d2aInst_0_io_output)
  );
  assign io_out_real = _d2aInst_0_io_output[63:32];
endmodule

module frac_sqrt(
  input         clock,
                reset,
                io_in_en,
  input  [24:0] io_in_a,
  output [22:0] io_out_s
);

  reg [46:0] P_0;
  reg [46:0] P_1;
  reg [46:0] P_2;
  reg [46:0] P_3;
  reg [46:0] P_4;
  reg [46:0] P_5;
  reg [46:0] P_6;
  reg [46:0] P_7;
  reg [46:0] P_8;
  reg [46:0] P_9;
  reg [46:0] P_10;
  reg [46:0] P_11;
  reg [46:0] P_12;
  reg [46:0] P_13;
  reg [47:0] X_0;
  reg [47:0] X_1;
  reg [47:0] X_2;
  reg [47:0] X_3;
  reg [47:0] X_4;
  reg [47:0] X_5;
  reg [47:0] X_6;
  reg [47:0] X_7;
  reg [47:0] X_8;
  reg [47:0] X_9;
  reg [47:0] X_10;
  reg [47:0] X_11;
  reg [47:0] X_12;
  reg [47:0] X_13;
  reg [22:0] results_0;
  reg [22:0] results_1;
  reg [22:0] results_2;
  reg [22:0] results_3;
  reg [22:0] results_4;
  reg [22:0] results_5;
  reg [22:0] results_6;
  reg [22:0] results_7;
  reg [22:0] results_8;
  reg [22:0] results_9;
  reg [22:0] results_10;
  reg [22:0] results_11;
  reg [22:0] results_12;
  reg [22:0] results_13;
  reg [22:0] results_14;
  always @(posedge clock) begin
    if (reset) begin
      P_0 <= 47'h0;
      P_1 <= 47'h0;
      P_2 <= 47'h0;
      P_3 <= 47'h0;
      P_4 <= 47'h0;
      P_5 <= 47'h0;
      P_6 <= 47'h0;
      P_7 <= 47'h0;
      P_8 <= 47'h0;
      P_9 <= 47'h0;
      P_10 <= 47'h0;
      P_11 <= 47'h0;
      P_12 <= 47'h0;
      P_13 <= 47'h0;
      X_0 <= 48'h0;
      X_1 <= 48'h0;
      X_2 <= 48'h0;
      X_3 <= 48'h0;
      X_4 <= 48'h0;
      X_5 <= 48'h0;
      X_6 <= 48'h0;
      X_7 <= 48'h0;
      X_8 <= 48'h0;
      X_9 <= 48'h0;
      X_10 <= 48'h0;
      X_11 <= 48'h0;
      X_12 <= 48'h0;
      X_13 <= 48'h0;
      results_0 <= 23'h0;
      results_1 <= 23'h0;
      results_2 <= 23'h0;
      results_3 <= 23'h0;
      results_4 <= 23'h0;
      results_5 <= 23'h0;
      results_6 <= 23'h0;
      results_7 <= 23'h0;
      results_8 <= 23'h0;
      results_9 <= 23'h0;
      results_10 <= 23'h0;
      results_11 <= 23'h0;
      results_12 <= 23'h0;
      results_13 <= 23'h0;
      results_14 <= 23'h0;
    end
    else if (io_in_en) begin
      automatic logic [47:0] _GEN = {io_in_a, 23'h0};
      automatic logic [47:0] _in_T_1 = _GEN - 48'h400000000000;
      automatic logic        yleqx = _in_T_1 > 48'h4FFFFFFFFFFF;
      automatic logic [47:0] y_1 = {2'h0, P_0[46:1]} + 48'h40000000000;
      automatic logic        yleqx_1 = y_1 <= X_0;
      automatic logic [47:0] y_2 = {3'h0, P_1[46:2]} + 48'h10000000000;
      automatic logic        yleqx_2 = y_2 <= X_1;
      automatic logic [47:0] y_3 = {4'h0, P_2[46:3]} + 48'h4000000000;
      automatic logic        yleqx_3 = y_3 <= X_2;
      automatic logic [47:0] y_4 = {5'h0, P_3[46:4]} + 48'h1000000000;
      automatic logic        yleqx_4 = y_4 <= X_3;
      automatic logic [47:0] y_5 = {6'h0, P_4[46:5]} + 48'h400000000;
      automatic logic        yleqx_5 = y_5 <= X_4;
      automatic logic [47:0] y_6 = {7'h0, P_5[46:6]} + 48'h100000000;
      automatic logic        yleqx_6 = y_6 <= X_5;
      automatic logic [47:0] y_7 = {8'h0, P_6[46:7]} + 48'h40000000;
      automatic logic        yleqx_7 = y_7 <= X_6;
      automatic logic [47:0] y_8 = {9'h0, P_7[46:8]} + 48'h10000000;
      automatic logic        yleqx_8 = y_8 <= X_7;
      automatic logic [47:0] y_9 = {10'h0, P_8[46:9]} + 48'h4000000;
      automatic logic        yleqx_9 = y_9 <= X_8;
      automatic logic [47:0] y_10 = {11'h0, P_9[46:10]} + 48'h1000000;
      automatic logic        yleqx_10 = y_10 <= X_9;
      automatic logic [47:0] y_11 = {12'h0, P_10[46:11]} + 48'h400000;
      automatic logic        yleqx_11 = y_11 <= X_10;
      automatic logic [47:0] y_12 = {13'h0, P_11[46:12]} + 48'h100000;
      automatic logic        yleqx_12 = y_12 <= X_11;
      automatic logic [47:0] y_13 = {14'h0, P_12[46:13]} + 48'h40000;
      automatic logic        yleqx_13 = y_13 <= X_12;
      P_0 <= {1'h1, yleqx, 45'h0};
      P_1 <= yleqx_1 ? P_0 + 47'h100000000000 : P_0;
      P_2 <= yleqx_2 ? P_1 + 47'h80000000000 : P_1;
      P_3 <= yleqx_3 ? P_2 + 47'h40000000000 : P_2;
      P_4 <= yleqx_4 ? P_3 + 47'h20000000000 : P_3;
      P_5 <= yleqx_5 ? P_4 + 47'h10000000000 : P_4;
      P_6 <= yleqx_6 ? P_5 + 47'h8000000000 : P_5;
      P_7 <= yleqx_7 ? P_6 + 47'h4000000000 : P_6;
      P_8 <= yleqx_8 ? P_7 + 47'h2000000000 : P_7;
      P_9 <= yleqx_9 ? P_8 + 47'h1000000000 : P_8;
      P_10 <= yleqx_10 ? P_9 + 47'h800000000 : P_9;
      P_11 <= yleqx_11 ? P_10 + 47'h400000000 : P_10;
      P_12 <= yleqx_12 ? P_11 + 47'h200000000 : P_11;
      P_13 <= yleqx_13 ? P_12 + 47'h100000000 : P_12;
      X_0 <= yleqx ? _GEN + 48'h700000000000 : _in_T_1;
      X_1 <= yleqx_1 ? X_0 - y_1 : X_0;
      X_2 <= yleqx_2 ? X_1 - y_2 : X_1;
      X_3 <= yleqx_3 ? X_2 - y_3 : X_2;
      X_4 <= yleqx_4 ? X_3 - y_4 : X_3;
      X_5 <= yleqx_5 ? X_4 - y_5 : X_4;
      X_6 <= yleqx_6 ? X_5 - y_6 : X_5;
      X_7 <= yleqx_7 ? X_6 - y_7 : X_6;
      X_8 <= yleqx_8 ? X_7 - y_8 : X_7;
      X_9 <= yleqx_9 ? X_8 - y_9 : X_8;
      X_10 <= yleqx_10 ? X_9 - y_10 : X_9;
      X_11 <= yleqx_11 ? X_10 - y_11 : X_10;
      X_12 <= yleqx_12 ? X_11 - y_12 : X_11;
      X_13 <= yleqx_13 ? X_12 - y_13 : X_12;
      results_0 <= {yleqx, 22'h0};
      results_1 <= {results_0[22], yleqx_1, results_0[20:0]};
      results_2 <= {results_1[22:21], yleqx_2, results_1[19:0]};
      results_3 <= {results_2[22:20], yleqx_3, results_2[18:0]};
      results_4 <= {results_3[22:19], yleqx_4, results_3[17:0]};
      results_5 <= {results_4[22:18], yleqx_5, results_4[16:0]};
      results_6 <= {results_5[22:17], yleqx_6, results_5[15:0]};
      results_7 <= {results_6[22:16], yleqx_7, results_6[14:0]};
      results_8 <= {results_7[22:15], yleqx_8, results_7[13:0]};
      results_9 <= {results_8[22:14], yleqx_9, results_8[12:0]};
      results_10 <= {results_9[22:13], yleqx_10, results_9[11:0]};
      results_11 <= {results_10[22:12], yleqx_11, results_10[10:0]};
      results_12 <= {results_11[22:11], yleqx_12, results_11[9:0]};
      results_13 <= {results_12[22:10], yleqx_13, results_12[8:0]};
      results_14 <=
        {results_13[22:9], {15'h0, P_13[46:14]} + 48'h10000 <= X_13, results_13[7:0]};
    end
  end // always @(posedge)
  assign io_out_s = results_14;
endmodule

module FP_sqrt_32_15(
  input         clock,
                reset,
                io_in_en,
  input  [31:0] io_in_a,
  output [31:0] io_out_s
);

  wire [22:0] _frac_sqrt_io_out_s;
  wire [8:0]  exp = {1'h0, io_in_a[30:23]} - 9'h7F;
  wire [7:0]  ref_exp = exp[8] ? ~(exp[7:0]) + 8'h1 : exp[7:0];
  reg         out_sign_r;
  reg         out_sign_r_1;
  reg         out_sign_r_2;
  reg         out_sign_r_3;
  reg         out_sign_r_4;
  reg         out_sign_r_5;
  reg         out_sign_r_6;
  reg         out_sign_r_7;
  reg         out_sign_r_8;
  reg         out_sign_r_9;
  reg         out_sign_r_10;
  reg         out_sign_r_11;
  reg         out_sign_r_12;
  reg         out_sign_r_13;
  reg         out_sign;
  reg  [6:0]  out_exp_r;
  reg  [6:0]  out_exp_r_1;
  reg  [6:0]  out_exp_r_2;
  reg  [6:0]  out_exp_r_3;
  reg  [6:0]  out_exp_r_4;
  reg  [6:0]  out_exp_r_5;
  reg  [6:0]  out_exp_r_6;
  reg  [6:0]  out_exp_r_7;
  reg  [6:0]  out_exp_r_8;
  reg  [6:0]  out_exp_r_9;
  reg  [6:0]  out_exp_r_10;
  reg  [6:0]  out_exp_r_11;
  reg  [6:0]  out_exp_r_12;
  reg  [6:0]  out_exp_r_13;
  reg  [6:0]  out_exp_r_14;
  always @(posedge clock) begin
    if (io_in_en) begin
      automatic logic [7:0] _exp_new_T_1 = ref_exp - 8'h1;
      out_sign_r <= io_in_a[31];
      out_sign_r_1 <= out_sign_r;
      out_sign_r_2 <= out_sign_r_1;
      out_sign_r_3 <= out_sign_r_2;
      out_sign_r_4 <= out_sign_r_3;
      out_sign_r_5 <= out_sign_r_4;
      out_sign_r_6 <= out_sign_r_5;
      out_sign_r_7 <= out_sign_r_6;
      out_sign_r_8 <= out_sign_r_7;
      out_sign_r_9 <= out_sign_r_8;
      out_sign_r_10 <= out_sign_r_9;
      out_sign_r_11 <= out_sign_r_10;
      out_sign_r_12 <= out_sign_r_11;
      out_sign_r_13 <= out_sign_r_12;
      out_sign <= out_sign_r_13;
      out_exp_r <= ref_exp[0] ? _exp_new_T_1[7:1] : ref_exp[7:1];
      out_exp_r_1 <= out_exp_r;
      out_exp_r_2 <= out_exp_r_1;
      out_exp_r_3 <= out_exp_r_2;
      out_exp_r_4 <= out_exp_r_3;
      out_exp_r_5 <= out_exp_r_4;
      out_exp_r_6 <= out_exp_r_5;
      out_exp_r_7 <= out_exp_r_6;
      out_exp_r_8 <= out_exp_r_7;
      out_exp_r_9 <= out_exp_r_8;
      out_exp_r_10 <= out_exp_r_9;
      out_exp_r_11 <= out_exp_r_10;
      out_exp_r_12 <= out_exp_r_11;
      out_exp_r_13 <= out_exp_r_12;
      out_exp_r_14 <= out_exp_r_13;
    end
  end // always @(posedge)
  frac_sqrt frac_sqrt (
    .clock    (clock),
    .reset    (reset),
    .io_in_en (io_in_en),
    .io_in_a  (ref_exp[0] ? {1'h1, io_in_a[22:0], 1'h0} : {2'h1, io_in_a[22:0]}),
    .io_out_s (_frac_sqrt_io_out_s)
  );
  assign io_out_s = {out_sign, {1'h0, out_exp_r_14} + 8'h7F, _frac_sqrt_io_out_s};
endmodule

module divider_BW25(
  input         clock,
                reset,
                io_in_ready,
  input  [24:0] io_in_a,
                io_in_b,
  output [24:0] io_out_s
);

  reg [49:0] a_aux_reg_0;
  reg [49:0] a_aux_reg_1;
  reg [49:0] a_aux_reg_2;
  reg [49:0] a_aux_reg_3;
  reg [49:0] a_aux_reg_4;
  reg [49:0] a_aux_reg_5;
  reg [49:0] a_aux_reg_6;
  reg [49:0] a_aux_reg_7;
  reg [49:0] a_aux_reg_8;
  reg [49:0] b_aux_reg_0;
  reg [49:0] b_aux_reg_1;
  reg [49:0] b_aux_reg_2;
  reg [49:0] b_aux_reg_3;
  reg [49:0] b_aux_reg_4;
  reg [49:0] b_aux_reg_5;
  reg [49:0] b_aux_reg_6;
  reg [49:0] b_aux_reg_7;
  reg [49:0] b_aux_reg_8;
  reg [24:0] result_reg_0;
  reg [24:0] result_reg_1;
  reg [24:0] result_reg_2;
  reg [24:0] result_reg_3;
  reg [24:0] result_reg_4;
  reg [24:0] result_reg_5;
  reg [24:0] result_reg_6;
  reg [24:0] result_reg_7;
  reg [24:0] result_reg_8;
  reg [24:0] result_reg_9;
  always @(posedge clock) begin
    if (reset) begin
      a_aux_reg_0 <= 50'h0;
      a_aux_reg_1 <= 50'h0;
      a_aux_reg_2 <= 50'h0;
      a_aux_reg_3 <= 50'h0;
      a_aux_reg_4 <= 50'h0;
      a_aux_reg_5 <= 50'h0;
      a_aux_reg_6 <= 50'h0;
      a_aux_reg_7 <= 50'h0;
      a_aux_reg_8 <= 50'h0;
      b_aux_reg_0 <= 50'h0;
      b_aux_reg_1 <= 50'h0;
      b_aux_reg_2 <= 50'h0;
      b_aux_reg_3 <= 50'h0;
      b_aux_reg_4 <= 50'h0;
      b_aux_reg_5 <= 50'h0;
      b_aux_reg_6 <= 50'h0;
      b_aux_reg_7 <= 50'h0;
      b_aux_reg_8 <= 50'h0;
      result_reg_0 <= 25'h0;
      result_reg_1 <= 25'h0;
      result_reg_2 <= 25'h0;
      result_reg_3 <= 25'h0;
      result_reg_4 <= 25'h0;
      result_reg_5 <= 25'h0;
      result_reg_6 <= 25'h0;
      result_reg_7 <= 25'h0;
      result_reg_8 <= 25'h0;
      result_reg_9 <= 25'h0;
    end
    else if (io_in_ready) begin
      automatic logic        t_24 = io_in_a >= io_in_b;
      automatic logic [49:0] _GEN = {1'h0, b_aux_reg_0[49:1]};
      automatic logic        t_1_23 = a_aux_reg_0 >= _GEN;
      automatic logic [49:0] _GEN_0 = {1'h0, b_aux_reg_1[49:1]};
      automatic logic        t_2_22 = a_aux_reg_1 >= _GEN_0;
      automatic logic [49:0] _GEN_1 = {1'h0, b_aux_reg_2[49:1]};
      automatic logic        t_3_21 = a_aux_reg_2 >= _GEN_1;
      automatic logic [49:0] _GEN_2 = {1'h0, b_aux_reg_3[49:1]};
      automatic logic        t_4_20 = a_aux_reg_3 >= _GEN_2;
      automatic logic [49:0] _GEN_3 = {1'h0, b_aux_reg_4[49:1]};
      automatic logic        t_5_19 = a_aux_reg_4 >= _GEN_3;
      automatic logic [49:0] _GEN_4 = {1'h0, b_aux_reg_5[49:1]};
      automatic logic        t_6_18 = a_aux_reg_5 >= _GEN_4;
      automatic logic [49:0] _GEN_5 = {1'h0, b_aux_reg_6[49:1]};
      automatic logic        t_7_17 = a_aux_reg_6 >= _GEN_5;
      automatic logic [49:0] _GEN_6 = {1'h0, b_aux_reg_7[49:1]};
      automatic logic        t_8_16 = a_aux_reg_7 >= _GEN_6;
      a_aux_reg_0 <= t_24 ? {io_in_a, 25'h0} - {io_in_b, 25'h0} : {io_in_a, 25'h0};
      a_aux_reg_1 <= t_1_23 ? a_aux_reg_0 - _GEN : a_aux_reg_0;
      a_aux_reg_2 <= t_2_22 ? a_aux_reg_1 - _GEN_0 : a_aux_reg_1;
      a_aux_reg_3 <= t_3_21 ? a_aux_reg_2 - _GEN_1 : a_aux_reg_2;
      a_aux_reg_4 <= t_4_20 ? a_aux_reg_3 - _GEN_2 : a_aux_reg_3;
      a_aux_reg_5 <= t_5_19 ? a_aux_reg_4 - _GEN_3 : a_aux_reg_4;
      a_aux_reg_6 <= t_6_18 ? a_aux_reg_5 - _GEN_4 : a_aux_reg_5;
      a_aux_reg_7 <= t_7_17 ? a_aux_reg_6 - _GEN_5 : a_aux_reg_6;
      a_aux_reg_8 <= t_8_16 ? a_aux_reg_7 - _GEN_6 : a_aux_reg_7;
      b_aux_reg_0 <= {io_in_b, 25'h0};
      b_aux_reg_1 <= _GEN;
      b_aux_reg_2 <= _GEN_0;
      b_aux_reg_3 <= _GEN_1;
      b_aux_reg_4 <= _GEN_2;
      b_aux_reg_5 <= _GEN_3;
      b_aux_reg_6 <= _GEN_4;
      b_aux_reg_7 <= _GEN_5;
      b_aux_reg_8 <= _GEN_6;
      result_reg_0 <= {t_24, 24'h0};
      result_reg_1 <= {result_reg_0[24], t_1_23, result_reg_0[22:0]};
      result_reg_2 <= {result_reg_1[24:23], t_2_22, result_reg_1[21:0]};
      result_reg_3 <= {result_reg_2[24:22], t_3_21, result_reg_2[20:0]};
      result_reg_4 <= {result_reg_3[24:21], t_4_20, result_reg_3[19:0]};
      result_reg_5 <= {result_reg_4[24:20], t_5_19, result_reg_4[18:0]};
      result_reg_6 <= {result_reg_5[24:19], t_6_18, result_reg_5[17:0]};
      result_reg_7 <= {result_reg_6[24:18], t_7_17, result_reg_6[16:0]};
      result_reg_8 <= {result_reg_7[24:17], t_8_16, result_reg_7[15:0]};
      result_reg_9 <=
        {result_reg_8[24:16],
         a_aux_reg_8 >= {1'h0, b_aux_reg_8[49:1]},
         result_reg_8[14:0]};
    end
  end // always @(posedge)
  assign io_out_s = result_reg_9;
endmodule

module FP_divider_32_10(
  input         clock,
                reset,
                io_in_en,
  input  [31:0] io_in_a,
                io_in_b,
  output [31:0] io_out_s
);

  wire [24:0] _divider_BW25_io_out_s;
  wire [7:0]  _postProcess_exp_subtractor_io_out_s;
  wire        _postProcess_exp_subtractor_io_out_c;
  wire [7:0]  exp_wire_1 =
    (&(io_in_b[30:23])) ? 8'hFE : io_in_b[30:23] == 8'h0 ? 8'h1 : io_in_b[30:23];
  reg         uo_check_r;
  reg         uo_check_r_1;
  reg         uo_check_r_2;
  reg         uo_check_r_3;
  reg         uo_check_r_4;
  reg         uo_check_r_5;
  reg         uo_check_r_6;
  reg         uo_check_r_7;
  reg         uo_check_r_8;
  reg         uo_check;
  reg         carry_flag_r;
  reg         carry_flag_r_1;
  reg         carry_flag_r_2;
  reg         carry_flag_r_3;
  reg         carry_flag_r_4;
  reg         carry_flag_r_5;
  reg         carry_flag_r_6;
  reg         carry_flag_r_7;
  reg         carry_flag_r_8;
  reg         carry_flag;
  reg  [7:0]  exp_sum_r;
  reg  [7:0]  exp_sum_r_1;
  reg  [7:0]  exp_sum_r_2;
  reg  [7:0]  exp_sum_r_3;
  reg  [7:0]  exp_sum_r_4;
  reg  [7:0]  exp_sum_r_5;
  reg  [7:0]  exp_sum_r_6;
  reg  [7:0]  exp_sum_r_7;
  reg  [7:0]  exp_sum_r_8;
  reg  [7:0]  exp_sum;
  reg         new_sign_reg_r;
  reg         new_sign_reg_r_1;
  reg         new_sign_reg_r_2;
  reg         new_sign_reg_r_3;
  reg         new_sign_reg_r_4;
  reg         new_sign_reg_r_5;
  reg         new_sign_reg_r_6;
  reg         new_sign_reg_r_7;
  reg         new_sign_reg_r_8;
  reg         new_sign_reg;
  wire [8:0]  _GEN = {1'h0, exp_sum};
  wire [8:0]  _GEN_0 = {8'h0, ~(_divider_BW25_io_out_s[24])};
  wire        o_flag_reg = uo_check & (~carry_flag | _GEN - _GEN_0 > 9'hFE);
  wire        u_flag_reg = ~uo_check & (carry_flag | _GEN - _GEN_0 == 9'h0);
  always @(posedge clock) begin
    if (io_in_en) begin
      uo_check_r <= exp_wire_1 < 8'h7F;
      uo_check_r_1 <= uo_check_r;
      uo_check_r_2 <= uo_check_r_1;
      uo_check_r_3 <= uo_check_r_2;
      uo_check_r_4 <= uo_check_r_3;
      uo_check_r_5 <= uo_check_r_4;
      uo_check_r_6 <= uo_check_r_5;
      uo_check_r_7 <= uo_check_r_6;
      uo_check_r_8 <= uo_check_r_7;
      uo_check <= uo_check_r_8;
      carry_flag_r <= _postProcess_exp_subtractor_io_out_c;
      carry_flag_r_1 <= carry_flag_r;
      carry_flag_r_2 <= carry_flag_r_1;
      carry_flag_r_3 <= carry_flag_r_2;
      carry_flag_r_4 <= carry_flag_r_3;
      carry_flag_r_5 <= carry_flag_r_4;
      carry_flag_r_6 <= carry_flag_r_5;
      carry_flag_r_7 <= carry_flag_r_6;
      carry_flag_r_8 <= carry_flag_r_7;
      carry_flag <= carry_flag_r_8;
      exp_sum_r <= _postProcess_exp_subtractor_io_out_s;
      exp_sum_r_1 <= exp_sum_r;
      exp_sum_r_2 <= exp_sum_r_1;
      exp_sum_r_3 <= exp_sum_r_2;
      exp_sum_r_4 <= exp_sum_r_3;
      exp_sum_r_5 <= exp_sum_r_4;
      exp_sum_r_6 <= exp_sum_r_5;
      exp_sum_r_7 <= exp_sum_r_6;
      exp_sum_r_8 <= exp_sum_r_7;
      exp_sum <= exp_sum_r_8;
      new_sign_reg_r <= io_in_a[31] ^ io_in_b[31];
      new_sign_reg_r_1 <= new_sign_reg_r;
      new_sign_reg_r_2 <= new_sign_reg_r_1;
      new_sign_reg_r_3 <= new_sign_reg_r_2;
      new_sign_reg_r_4 <= new_sign_reg_r_3;
      new_sign_reg_r_5 <= new_sign_reg_r_4;
      new_sign_reg_r_6 <= new_sign_reg_r_5;
      new_sign_reg_r_7 <= new_sign_reg_r_6;
      new_sign_reg_r_8 <= new_sign_reg_r_7;
      new_sign_reg <= new_sign_reg_r_8;
    end
  end // always @(posedge)
  full_subtractor postProcess_exp_subtractor (
    .io_in_a
      ((&(io_in_a[30:23])) ? 8'hFE : io_in_a[30:23] == 8'h0 ? 8'h1 : io_in_a[30:23]),
    .io_in_b  (exp_wire_1 - 8'h7F),
    .io_out_s (_postProcess_exp_subtractor_io_out_s),
    .io_out_c (_postProcess_exp_subtractor_io_out_c)
  );
  divider_BW25 divider_BW25 (
    .clock       (clock),
    .reset       (reset),
    .io_in_ready (io_in_en),
    .io_in_a     ({1'h1, io_in_a[22:0], 1'h0}),
    .io_in_b     ({1'h1, io_in_b[22:0], 1'h0}),
    .io_out_s    (_divider_BW25_io_out_s)
  );
  assign io_out_s =
    {new_sign_reg,
     o_flag_reg
       ? 8'hFE
       : u_flag_reg ? 8'h1 : _divider_BW25_io_out_s[24] ? exp_sum : exp_sum - 8'h1,
     o_flag_reg
       ? 23'h7FFFFF
       : u_flag_reg
           ? 23'h0
           : _divider_BW25_io_out_s[24]
               ? _divider_BW25_io_out_s[23:1]
               : _divider_BW25_io_out_s[22:0]};
endmodule

module alpha(
  input         clock,
                reset,
  input  [63:0] io_in_x0,
  input  [31:0] io_in_eu_norm,
  input         io_in_en,
                io_counter_reset,
  output [63:0] io_out_s
);

  wire [31:0] _divider_1_io_out_s;
  wire [31:0] _divider_0_io_out_s;
  wire [31:0] _sqrt_io_out_s;
  wire [31:0] _adder_io_out_s;
  wire [31:0] _mult_3_io_out_s;
  wire [31:0] _mult_2_io_out_s;
  wire [31:0] _mult_1_io_out_s;
  wire [31:0] _mult_0_io_out_s;
  reg  [31:0] counter;
  reg  [31:0] eu_norm_reg;
  wire [31:0] _GEN = io_in_en ? io_in_x0[63:32] : 32'h0;
  wire [31:0] _GEN_0 = io_in_en ? io_in_x0[31:0] : 32'h0;
  wire        _GEN_1 = counter > 32'h9;
  wire        _GEN_2 = counter > 32'h16;
  reg  [31:0] x0_real_shift_r;
  reg  [31:0] x0_real_shift_r_1;
  reg  [31:0] x0_real_shift_r_2;
  reg  [31:0] x0_real_shift_r_3;
  reg  [31:0] x0_real_shift_r_4;
  reg  [31:0] x0_real_shift_r_5;
  reg  [31:0] x0_real_shift_r_6;
  reg  [31:0] x0_real_shift_r_7;
  reg  [31:0] x0_real_shift_r_8;
  reg  [31:0] x0_real_shift_r_9;
  reg  [31:0] x0_real_shift_r_10;
  reg  [31:0] x0_real_shift_r_11;
  reg  [31:0] x0_real_shift_r_12;
  reg  [31:0] x0_real_shift_r_13;
  reg  [31:0] x0_real_shift_r_14;
  reg  [31:0] x0_real_shift_r_15;
  reg  [31:0] x0_real_shift_r_16;
  reg  [31:0] x0_real_shift_r_17;
  reg  [31:0] x0_real_shift_r_18;
  reg  [31:0] x0_real_shift_r_19;
  reg  [31:0] x0_real_shift_r_20;
  reg  [31:0] x0_real_shift_r_21;
  reg  [31:0] x0_real_shift_r_22;
  reg  [31:0] x0_real_shift_r_23;
  reg  [31:0] x0_real_shift_r_24;
  reg  [31:0] x0_real_shift_r_25;
  reg  [31:0] x0_real_shift_r_26;
  reg  [31:0] x0_real_shift_r_27;
  reg  [31:0] x0_real_shift_r_28;
  reg  [31:0] x0_real_shift_r_29;
  reg  [31:0] x0_real_shift_r_30;
  reg  [31:0] x0_real_shift_r_31;
  reg  [31:0] x0_real_shift;
  reg  [31:0] x0_imag_shift_r;
  reg  [31:0] x0_imag_shift_r_1;
  reg  [31:0] x0_imag_shift_r_2;
  reg  [31:0] x0_imag_shift_r_3;
  reg  [31:0] x0_imag_shift_r_4;
  reg  [31:0] x0_imag_shift_r_5;
  reg  [31:0] x0_imag_shift_r_6;
  reg  [31:0] x0_imag_shift_r_7;
  reg  [31:0] x0_imag_shift_r_8;
  reg  [31:0] x0_imag_shift_r_9;
  reg  [31:0] x0_imag_shift_r_10;
  reg  [31:0] x0_imag_shift_r_11;
  reg  [31:0] x0_imag_shift_r_12;
  reg  [31:0] x0_imag_shift_r_13;
  reg  [31:0] x0_imag_shift_r_14;
  reg  [31:0] x0_imag_shift_r_15;
  reg  [31:0] x0_imag_shift_r_16;
  reg  [31:0] x0_imag_shift_r_17;
  reg  [31:0] x0_imag_shift_r_18;
  reg  [31:0] x0_imag_shift_r_19;
  reg  [31:0] x0_imag_shift_r_20;
  reg  [31:0] x0_imag_shift_r_21;
  reg  [31:0] x0_imag_shift_r_22;
  reg  [31:0] x0_imag_shift_r_23;
  reg  [31:0] x0_imag_shift_r_24;
  reg  [31:0] x0_imag_shift_r_25;
  reg  [31:0] x0_imag_shift_r_26;
  reg  [31:0] x0_imag_shift_r_27;
  reg  [31:0] x0_imag_shift_r_28;
  reg  [31:0] x0_imag_shift_r_29;
  reg  [31:0] x0_imag_shift_r_30;
  reg  [31:0] x0_imag_shift_r_31;
  reg  [31:0] x0_imag_shift;
  wire        _GEN_3 = counter > 32'h25;
  wire [31:0] _GEN_4 = _GEN_3 ? _sqrt_io_out_s : 32'h0;
  wire        _GEN_5 = counter > 32'h2F;
  wire [31:0] _GEN_6 = _GEN_5 ? eu_norm_reg : 32'h0;
  always @(posedge clock) begin
    if (reset) begin
      counter <= 32'h0;
      eu_norm_reg <= 32'h0;
    end
    else begin
      if (io_counter_reset)
        counter <= 32'h0;
      else if (io_in_en & counter < 32'h3B)
        counter <= counter + 32'h1;
      if (counter == 32'h0)
        eu_norm_reg <= io_in_eu_norm;
    end
    if (io_in_en) begin
      x0_real_shift_r <= io_in_x0[63:32];
      x0_real_shift_r_1 <= x0_real_shift_r;
      x0_real_shift_r_2 <= x0_real_shift_r_1;
      x0_real_shift_r_3 <= x0_real_shift_r_2;
      x0_real_shift_r_4 <= x0_real_shift_r_3;
      x0_real_shift_r_5 <= x0_real_shift_r_4;
      x0_real_shift_r_6 <= x0_real_shift_r_5;
      x0_real_shift_r_7 <= x0_real_shift_r_6;
      x0_real_shift_r_8 <= x0_real_shift_r_7;
      x0_real_shift_r_9 <= x0_real_shift_r_8;
      x0_real_shift_r_10 <= x0_real_shift_r_9;
      x0_real_shift_r_11 <= x0_real_shift_r_10;
      x0_real_shift_r_12 <= x0_real_shift_r_11;
      x0_real_shift_r_13 <= x0_real_shift_r_12;
      x0_real_shift_r_14 <= x0_real_shift_r_13;
      x0_real_shift_r_15 <= x0_real_shift_r_14;
      x0_real_shift_r_16 <= x0_real_shift_r_15;
      x0_real_shift_r_17 <= x0_real_shift_r_16;
      x0_real_shift_r_18 <= x0_real_shift_r_17;
      x0_real_shift_r_19 <= x0_real_shift_r_18;
      x0_real_shift_r_20 <= x0_real_shift_r_19;
      x0_real_shift_r_21 <= x0_real_shift_r_20;
      x0_real_shift_r_22 <= x0_real_shift_r_21;
      x0_real_shift_r_23 <= x0_real_shift_r_22;
      x0_real_shift_r_24 <= x0_real_shift_r_23;
      x0_real_shift_r_25 <= x0_real_shift_r_24;
      x0_real_shift_r_26 <= x0_real_shift_r_25;
      x0_real_shift_r_27 <= x0_real_shift_r_26;
      x0_real_shift_r_28 <= x0_real_shift_r_27;
      x0_real_shift_r_29 <= x0_real_shift_r_28;
      x0_real_shift_r_30 <= x0_real_shift_r_29;
      x0_real_shift_r_31 <= x0_real_shift_r_30;
      x0_real_shift <= x0_real_shift_r_31;
      x0_imag_shift_r <= io_in_x0[31:0];
      x0_imag_shift_r_1 <= x0_imag_shift_r;
      x0_imag_shift_r_2 <= x0_imag_shift_r_1;
      x0_imag_shift_r_3 <= x0_imag_shift_r_2;
      x0_imag_shift_r_4 <= x0_imag_shift_r_3;
      x0_imag_shift_r_5 <= x0_imag_shift_r_4;
      x0_imag_shift_r_6 <= x0_imag_shift_r_5;
      x0_imag_shift_r_7 <= x0_imag_shift_r_6;
      x0_imag_shift_r_8 <= x0_imag_shift_r_7;
      x0_imag_shift_r_9 <= x0_imag_shift_r_8;
      x0_imag_shift_r_10 <= x0_imag_shift_r_9;
      x0_imag_shift_r_11 <= x0_imag_shift_r_10;
      x0_imag_shift_r_12 <= x0_imag_shift_r_11;
      x0_imag_shift_r_13 <= x0_imag_shift_r_12;
      x0_imag_shift_r_14 <= x0_imag_shift_r_13;
      x0_imag_shift_r_15 <= x0_imag_shift_r_14;
      x0_imag_shift_r_16 <= x0_imag_shift_r_15;
      x0_imag_shift_r_17 <= x0_imag_shift_r_16;
      x0_imag_shift_r_18 <= x0_imag_shift_r_17;
      x0_imag_shift_r_19 <= x0_imag_shift_r_18;
      x0_imag_shift_r_20 <= x0_imag_shift_r_19;
      x0_imag_shift_r_21 <= x0_imag_shift_r_20;
      x0_imag_shift_r_22 <= x0_imag_shift_r_21;
      x0_imag_shift_r_23 <= x0_imag_shift_r_22;
      x0_imag_shift_r_24 <= x0_imag_shift_r_23;
      x0_imag_shift_r_25 <= x0_imag_shift_r_24;
      x0_imag_shift_r_26 <= x0_imag_shift_r_25;
      x0_imag_shift_r_27 <= x0_imag_shift_r_26;
      x0_imag_shift_r_28 <= x0_imag_shift_r_27;
      x0_imag_shift_r_29 <= x0_imag_shift_r_28;
      x0_imag_shift_r_30 <= x0_imag_shift_r_29;
      x0_imag_shift_r_31 <= x0_imag_shift_r_30;
      x0_imag_shift <= x0_imag_shift_r_31;
    end
  end // always @(posedge)
  FP_mult_32_10_v2 mult_0 (
    .clock    (clock),
    .io_in_en (io_in_en),
    .io_in_a  (_GEN),
    .io_in_b  (_GEN),
    .io_out_s (_mult_0_io_out_s)
  );
  FP_mult_32_10_v2 mult_1 (
    .clock    (clock),
    .io_in_en (io_in_en),
    .io_in_a  (_GEN_0),
    .io_in_b  (_GEN_0),
    .io_out_s (_mult_1_io_out_s)
  );
  FP_mult_32_10_v2 mult_2 (
    .clock    (clock),
    .io_in_en (_GEN_5),
    .io_in_a  (_GEN_6),
    .io_in_b  (_GEN_5 ? _divider_0_io_out_s : 32'h0),
    .io_out_s (_mult_2_io_out_s)
  );
  FP_mult_32_10_v2 mult_3 (
    .clock    (clock),
    .io_in_en (_GEN_5),
    .io_in_a  (_GEN_6),
    .io_in_b  (_GEN_5 ? _divider_1_io_out_s : 32'h0),
    .io_out_s (_mult_3_io_out_s)
  );
  FP_add_32_13 adder (
    .clock    (clock),
    .io_in_en (_GEN_1),
    .io_in_a  (_GEN_1 ? _mult_0_io_out_s : 32'h0),
    .io_in_b  (_GEN_1 ? _mult_1_io_out_s : 32'h0),
    .io_out_s (_adder_io_out_s)
  );
  FP_sqrt_32_15 sqrt (
    .clock    (clock),
    .reset    (reset),
    .io_in_en (_GEN_2),
    .io_in_a  (_GEN_2 ? _adder_io_out_s : 32'h0),
    .io_out_s (_sqrt_io_out_s)
  );
  FP_divider_32_10 divider_0 (
    .clock    (clock),
    .reset    (reset),
    .io_in_en (_GEN_3),
    .io_in_a  (_GEN_3 ? x0_real_shift : 32'h0),
    .io_in_b  (_GEN_4),
    .io_out_s (_divider_0_io_out_s)
  );
  FP_divider_32_10 divider_1 (
    .clock    (clock),
    .reset    (reset),
    .io_in_en (_GEN_3),
    .io_in_a  (_GEN_3 ? x0_imag_shift : 32'h0),
    .io_in_b  (_GEN_4),
    .io_out_s (_divider_1_io_out_s)
  );
  assign io_out_s = {_mult_2_io_out_s, _mult_3_io_out_s};
endmodule

module vk_gen(
  input         clock,
                reset,
  input  [63:0] io_xk_in_0,
                io_xk_in_1,
                io_alpha_in,
  input         io_in_en,
                io_counter_reset,
  output [63:0] io_out_s_0,
                io_out_s_1
);

  wire [63:0] _adder_io_out_s;
  reg  [31:0] counter;
  wire        _GEN = counter == 32'h0;
  reg  [63:0] shifted_xk_r;
  reg  [63:0] shifted_xk_r_1;
  reg  [63:0] shifted_xk_r_2;
  reg  [63:0] shifted_xk_r_3;
  reg  [63:0] shifted_xk_r_4;
  reg  [63:0] shifted_xk_r_5;
  reg  [63:0] shifted_xk_r_6;
  reg  [63:0] shifted_xk_r_7;
  reg  [63:0] shifted_xk_r_8;
  reg  [63:0] shifted_xk_r_9;
  reg  [63:0] shifted_xk_r_10;
  reg  [63:0] shifted_xk_r_11;
  reg  [63:0] shifted_xk_r_12;
  reg  [63:0] shifted_xk_r_13;
  reg  [63:0] shifted_xk_r_14;
  reg  [63:0] shifted_xk_r_15;
  reg  [63:0] shifted_xk_r_16;
  reg  [63:0] shifted_xk_r_17;
  reg  [63:0] shifted_xk_r_18;
  reg  [63:0] shifted_xk_r_19;
  reg  [63:0] shifted_xk_r_20;
  reg  [63:0] shifted_xk_r_21;
  reg  [63:0] shifted_xk_r_22;
  reg  [63:0] shifted_xk_r_23;
  reg  [63:0] shifted_xk_r_24;
  reg  [63:0] shifted_xk_r_25;
  always @(posedge clock) begin
    if (reset)
      counter <= 32'h0;
    else if (io_counter_reset)
      counter <= 32'h0;
    else if (io_in_en)
      counter <= counter + 32'h1;
    shifted_xk_r <= io_xk_in_0;
    shifted_xk_r_1 <= shifted_xk_r;
    shifted_xk_r_2 <= shifted_xk_r_1;
    shifted_xk_r_3 <= shifted_xk_r_2;
    shifted_xk_r_4 <= shifted_xk_r_3;
    shifted_xk_r_5 <= shifted_xk_r_4;
    shifted_xk_r_6 <= shifted_xk_r_5;
    shifted_xk_r_7 <= shifted_xk_r_6;
    shifted_xk_r_8 <= shifted_xk_r_7;
    shifted_xk_r_9 <= shifted_xk_r_8;
    shifted_xk_r_10 <= shifted_xk_r_9;
    shifted_xk_r_11 <= shifted_xk_r_10;
    shifted_xk_r_12 <= shifted_xk_r_11;
    shifted_xk_r_13 <= io_xk_in_1;
    shifted_xk_r_14 <= shifted_xk_r_13;
    shifted_xk_r_15 <= shifted_xk_r_14;
    shifted_xk_r_16 <= shifted_xk_r_15;
    shifted_xk_r_17 <= shifted_xk_r_16;
    shifted_xk_r_18 <= shifted_xk_r_17;
    shifted_xk_r_19 <= shifted_xk_r_18;
    shifted_xk_r_20 <= shifted_xk_r_19;
    shifted_xk_r_21 <= shifted_xk_r_20;
    shifted_xk_r_22 <= shifted_xk_r_21;
    shifted_xk_r_23 <= shifted_xk_r_22;
    shifted_xk_r_24 <= shifted_xk_r_23;
    shifted_xk_r_25 <= shifted_xk_r_24;
  end // always @(posedge)
  complex_adder adder (
    .clock       (clock),
    .io_complexA (_GEN ? io_xk_in_0 : 64'h0),
    .io_complexB (_GEN ? io_alpha_in : 64'h0),
    .io_in_en    (1'h1),
    .io_out_s    (_adder_io_out_s)
  );
  assign io_out_s_0 = counter == 32'hD ? _adder_io_out_s : shifted_xk_r_12;
  assign io_out_s_1 = shifted_xk_r_25;
endmodule

module tk_gen(
  input         clock,
                reset,
  input  [63:0] io_vk_in_0,
                io_vk_in_1,
  input         io_in_en,
                io_counter_reset,
  output [31:0] io_out_s
);

  wire [31:0] _divider_io_out_s;
  wire [31:0] _dot_io_out_real;
  reg  [31:0] out_s_reg;
  reg  [31:0] counter;
  wire [63:0] _GEN = io_in_en ? io_vk_in_0 : 64'h0;
  wire [63:0] _GEN_0 = io_in_en ? io_vk_in_1 : 64'h0;
  wire        _GEN_1 = counter > 32'h31;
  always @(posedge clock) begin
    if (reset) begin
      out_s_reg <= 32'h0;
      counter <= 32'h0;
    end
    else begin
      if (counter == 32'h3C)
        out_s_reg <= _divider_io_out_s;
      if (io_counter_reset)
        counter <= 32'h0;
      else if (io_in_en)
        counter <= counter + 32'h1;
    end
  end // always @(posedge)
  cmplx_dot_iterative dot (
    .clock            (clock),
    .reset            (reset),
    .io_vec_a_0       (_GEN),
    .io_vec_a_1       (_GEN_0),
    .io_vec_b_0       (_GEN),
    .io_vec_b_1       (_GEN_0),
    .io_counter_reset (io_in_en & io_counter_reset),
    .io_in_en         (io_in_en),
    .io_out_real      (_dot_io_out_real)
  );
  FP_divider_32_10 divider (
    .clock    (clock),
    .reset    (reset),
    .io_in_en (_GEN_1),
    .io_in_a  (_GEN_1 ? 32'hC0000000 : 32'h0),
    .io_in_b  (_GEN_1 ? _dot_io_out_real : 32'h0),
    .io_out_s (_divider_io_out_s)
  );
  assign io_out_s = out_s_reg;
endmodule

module tsqr_outer_loop(
  input         clock,
                reset,
  input  [63:0] io_xk_in_0,
                io_xk_in_1,
  input         io_in_valid,
                io_counter_reset,
                io_in_en,
  output [63:0] io_alpha_out,
  output [31:0] io_out_tk,
  output        io_out_valid
);

  wire [31:0] _sqrt_io_out_s;
  wire [31:0] _tk_gen_io_out_s;
  wire [63:0] _vk_gen_io_out_s_0;
  wire [63:0] _vk_gen_io_out_s_1;
  wire [63:0] _alpha_gen_io_out_s;
  wire [31:0] _eu_norm_dot_io_out_real;
  reg  [31:0] counter;
  reg  [63:0] x0_reg;
  reg  [63:0] shifted_x0_r;
  reg  [63:0] shifted_x0_r_1;
  reg  [63:0] shifted_x0_r_2;
  reg  [63:0] shifted_x0_r_3;
  reg  [63:0] shifted_x0_r_4;
  reg  [63:0] shifted_x0_r_5;
  reg  [63:0] shifted_x0_r_6;
  reg  [63:0] shifted_x0_r_7;
  reg  [63:0] shifted_x0_r_8;
  reg  [63:0] shifted_x0_r_9;
  reg  [63:0] shifted_x0_r_10;
  reg  [63:0] shifted_x0_r_11;
  reg  [63:0] shifted_x0_r_12;
  reg  [63:0] shifted_x0_r_13;
  reg  [63:0] shifted_x0_r_14;
  reg  [63:0] shifted_x0_r_15;
  reg  [63:0] shifted_x0_r_16;
  reg  [63:0] shifted_x0_r_17;
  reg  [63:0] shifted_x0_r_18;
  reg  [63:0] shifted_x0_r_19;
  reg  [63:0] shifted_x0_r_20;
  reg  [63:0] shifted_x0_r_21;
  reg  [63:0] shifted_x0_r_22;
  reg  [63:0] shifted_x0_r_23;
  reg  [63:0] shifted_x0_r_24;
  reg  [63:0] shifted_x0_r_25;
  reg  [63:0] shifted_x0_r_26;
  reg  [63:0] shifted_x0_r_27;
  reg  [63:0] shifted_x0_r_28;
  reg  [63:0] shifted_x0_r_29;
  reg  [63:0] shifted_x0_r_30;
  reg  [63:0] shifted_x0_r_31;
  reg  [63:0] shifted_x0_r_32;
  reg  [63:0] shifted_x0_r_33;
  reg  [63:0] shifted_x0_r_34;
  reg  [63:0] shifted_x0_r_35;
  reg  [63:0] shifted_x0_r_36;
  reg  [63:0] shifted_x0_r_37;
  reg  [63:0] shifted_x0_r_38;
  reg  [63:0] shifted_x0_r_39;
  reg  [63:0] shifted_x0_r_40;
  reg  [63:0] shifted_x0_r_41;
  reg  [63:0] shifted_x0_r_42;
  reg  [63:0] shifted_x0_r_43;
  reg  [63:0] shifted_x0_r_44;
  reg  [63:0] shifted_x0_r_45;
  reg  [63:0] shifted_x0_r_46;
  reg  [63:0] shifted_x0_r_47;
  reg  [63:0] shifted_x0_r_48;
  reg  [63:0] shifted_x0_r_49;
  reg  [63:0] shifted_x0_r_50;
  reg  [63:0] shifted_x0_r_51;
  reg  [63:0] shifted_x0_r_52;
  reg  [63:0] shifted_x0_r_53;
  reg  [63:0] shifted_x0_r_54;
  reg  [63:0] shifted_x0_r_55;
  reg  [63:0] shifted_x0_r_56;
  reg  [63:0] shifted_x0_r_57;
  reg  [63:0] shifted_x0_r_58;
  reg  [63:0] shifted_x0_r_59;
  reg  [63:0] shifted_x0_r_60;
  reg  [63:0] shifted_x0_r_61;
  reg  [63:0] shifted_x0_r_62;
  reg  [63:0] shifted_x0;
  reg  [63:0] shifted_xk_0_r;
  reg  [63:0] shifted_xk_0_r_1;
  reg  [63:0] shifted_xk_0_r_2;
  reg  [63:0] shifted_xk_0_r_3;
  reg  [63:0] shifted_xk_0_r_4;
  reg  [63:0] shifted_xk_0_r_5;
  reg  [63:0] shifted_xk_0_r_6;
  reg  [63:0] shifted_xk_0_r_7;
  reg  [63:0] shifted_xk_0_r_8;
  reg  [63:0] shifted_xk_0_r_9;
  reg  [63:0] shifted_xk_0_r_10;
  reg  [63:0] shifted_xk_0_r_11;
  reg  [63:0] shifted_xk_0_r_12;
  reg  [63:0] shifted_xk_0_r_13;
  reg  [63:0] shifted_xk_0_r_14;
  reg  [63:0] shifted_xk_0_r_15;
  reg  [63:0] shifted_xk_0_r_16;
  reg  [63:0] shifted_xk_0_r_17;
  reg  [63:0] shifted_xk_0_r_18;
  reg  [63:0] shifted_xk_0_r_19;
  reg  [63:0] shifted_xk_0_r_20;
  reg  [63:0] shifted_xk_0_r_21;
  reg  [63:0] shifted_xk_0_r_22;
  reg  [63:0] shifted_xk_0_r_23;
  reg  [63:0] shifted_xk_0_r_24;
  reg  [63:0] shifted_xk_0_r_25;
  reg  [63:0] shifted_xk_0_r_26;
  reg  [63:0] shifted_xk_0_r_27;
  reg  [63:0] shifted_xk_0_r_28;
  reg  [63:0] shifted_xk_0_r_29;
  reg  [63:0] shifted_xk_0_r_30;
  reg  [63:0] shifted_xk_0_r_31;
  reg  [63:0] shifted_xk_0_r_32;
  reg  [63:0] shifted_xk_0_r_33;
  reg  [63:0] shifted_xk_0_r_34;
  reg  [63:0] shifted_xk_0_r_35;
  reg  [63:0] shifted_xk_0_r_36;
  reg  [63:0] shifted_xk_0_r_37;
  reg  [63:0] shifted_xk_0_r_38;
  reg  [63:0] shifted_xk_0_r_39;
  reg  [63:0] shifted_xk_0_r_40;
  reg  [63:0] shifted_xk_0_r_41;
  reg  [63:0] shifted_xk_0_r_42;
  reg  [63:0] shifted_xk_0_r_43;
  reg  [63:0] shifted_xk_0_r_44;
  reg  [63:0] shifted_xk_0_r_45;
  reg  [63:0] shifted_xk_0_r_46;
  reg  [63:0] shifted_xk_0_r_47;
  reg  [63:0] shifted_xk_0_r_48;
  reg  [63:0] shifted_xk_0_r_49;
  reg  [63:0] shifted_xk_0_r_50;
  reg  [63:0] shifted_xk_0_r_51;
  reg  [63:0] shifted_xk_0_r_52;
  reg  [63:0] shifted_xk_0_r_53;
  reg  [63:0] shifted_xk_0_r_54;
  reg  [63:0] shifted_xk_0_r_55;
  reg  [63:0] shifted_xk_0_r_56;
  reg  [63:0] shifted_xk_0_r_57;
  reg  [63:0] shifted_xk_0_r_58;
  reg  [63:0] shifted_xk_0_r_59;
  reg  [63:0] shifted_xk_0_r_60;
  reg  [63:0] shifted_xk_0_r_61;
  reg  [63:0] shifted_xk_0_r_62;
  reg  [63:0] shifted_xk_0_r_63;
  reg  [63:0] shifted_xk_0_r_64;
  reg  [63:0] shifted_xk_0_r_65;
  reg  [63:0] shifted_xk_0_r_66;
  reg  [63:0] shifted_xk_0_r_67;
  reg  [63:0] shifted_xk_0_r_68;
  reg  [63:0] shifted_xk_0_r_69;
  reg  [63:0] shifted_xk_0_r_70;
  reg  [63:0] shifted_xk_0_r_71;
  reg  [63:0] shifted_xk_0_r_72;
  reg  [63:0] shifted_xk_0_r_73;
  reg  [63:0] shifted_xk_0_r_74;
  reg  [63:0] shifted_xk_0_r_75;
  reg  [63:0] shifted_xk_0_r_76;
  reg  [63:0] shifted_xk_0_r_77;
  reg  [63:0] shifted_xk_0_r_78;
  reg  [63:0] shifted_xk_0_r_79;
  reg  [63:0] shifted_xk_0_r_80;
  reg  [63:0] shifted_xk_0_r_81;
  reg  [63:0] shifted_xk_0_r_82;
  reg  [63:0] shifted_xk_0_r_83;
  reg  [63:0] shifted_xk_0_r_84;
  reg  [63:0] shifted_xk_0_r_85;
  reg  [63:0] shifted_xk_0_r_86;
  reg  [63:0] shifted_xk_0_r_87;
  reg  [63:0] shifted_xk_0_r_88;
  reg  [63:0] shifted_xk_0_r_89;
  reg  [63:0] shifted_xk_0_r_90;
  reg  [63:0] shifted_xk_0_r_91;
  reg  [63:0] shifted_xk_0_r_92;
  reg  [63:0] shifted_xk_0_r_93;
  reg  [63:0] shifted_xk_0_r_94;
  reg  [63:0] shifted_xk_0_r_95;
  reg  [63:0] shifted_xk_0_r_96;
  reg  [63:0] shifted_xk_0_r_97;
  reg  [63:0] shifted_xk_0_r_98;
  reg  [63:0] shifted_xk_0_r_99;
  reg  [63:0] shifted_xk_0_r_100;
  reg  [63:0] shifted_xk_0_r_101;
  reg  [63:0] shifted_xk_0_r_102;
  reg  [63:0] shifted_xk_0_r_103;
  reg  [63:0] shifted_xk_0_r_104;
  reg  [63:0] shifted_xk_0_r_105;
  reg  [63:0] shifted_xk_0_r_106;
  reg  [63:0] shifted_xk_0_r_107;
  reg  [63:0] shifted_xk_0_r_108;
  reg  [63:0] shifted_xk_0_r_109;
  reg  [63:0] shifted_xk_0_r_110;
  reg  [63:0] shifted_xk_0_r_111;
  reg  [63:0] shifted_xk_0_r_112;
  reg  [63:0] shifted_xk_0_r_113;
  reg  [63:0] shifted_xk_0_r_114;
  reg  [63:0] shifted_xk_0_r_115;
  reg  [63:0] shifted_xk_0_r_116;
  reg  [63:0] shifted_xk_0_r_117;
  reg  [63:0] shifted_xk_0_r_118;
  reg  [63:0] shifted_xk_0_r_119;
  reg  [63:0] shifted_xk_0_r_120;
  reg  [63:0] shifted_xk_0_r_121;
  reg  [63:0] shifted_xk_0_r_122;
  reg  [63:0] shifted_xk_1_r;
  reg  [63:0] shifted_xk_1_r_1;
  reg  [63:0] shifted_xk_1_r_2;
  reg  [63:0] shifted_xk_1_r_3;
  reg  [63:0] shifted_xk_1_r_4;
  reg  [63:0] shifted_xk_1_r_5;
  reg  [63:0] shifted_xk_1_r_6;
  reg  [63:0] shifted_xk_1_r_7;
  reg  [63:0] shifted_xk_1_r_8;
  reg  [63:0] shifted_xk_1_r_9;
  reg  [63:0] shifted_xk_1_r_10;
  reg  [63:0] shifted_xk_1_r_11;
  reg  [63:0] shifted_xk_1_r_12;
  reg  [63:0] shifted_xk_1_r_13;
  reg  [63:0] shifted_xk_1_r_14;
  reg  [63:0] shifted_xk_1_r_15;
  reg  [63:0] shifted_xk_1_r_16;
  reg  [63:0] shifted_xk_1_r_17;
  reg  [63:0] shifted_xk_1_r_18;
  reg  [63:0] shifted_xk_1_r_19;
  reg  [63:0] shifted_xk_1_r_20;
  reg  [63:0] shifted_xk_1_r_21;
  reg  [63:0] shifted_xk_1_r_22;
  reg  [63:0] shifted_xk_1_r_23;
  reg  [63:0] shifted_xk_1_r_24;
  reg  [63:0] shifted_xk_1_r_25;
  reg  [63:0] shifted_xk_1_r_26;
  reg  [63:0] shifted_xk_1_r_27;
  reg  [63:0] shifted_xk_1_r_28;
  reg  [63:0] shifted_xk_1_r_29;
  reg  [63:0] shifted_xk_1_r_30;
  reg  [63:0] shifted_xk_1_r_31;
  reg  [63:0] shifted_xk_1_r_32;
  reg  [63:0] shifted_xk_1_r_33;
  reg  [63:0] shifted_xk_1_r_34;
  reg  [63:0] shifted_xk_1_r_35;
  reg  [63:0] shifted_xk_1_r_36;
  reg  [63:0] shifted_xk_1_r_37;
  reg  [63:0] shifted_xk_1_r_38;
  reg  [63:0] shifted_xk_1_r_39;
  reg  [63:0] shifted_xk_1_r_40;
  reg  [63:0] shifted_xk_1_r_41;
  reg  [63:0] shifted_xk_1_r_42;
  reg  [63:0] shifted_xk_1_r_43;
  reg  [63:0] shifted_xk_1_r_44;
  reg  [63:0] shifted_xk_1_r_45;
  reg  [63:0] shifted_xk_1_r_46;
  reg  [63:0] shifted_xk_1_r_47;
  reg  [63:0] shifted_xk_1_r_48;
  reg  [63:0] shifted_xk_1_r_49;
  reg  [63:0] shifted_xk_1_r_50;
  reg  [63:0] shifted_xk_1_r_51;
  reg  [63:0] shifted_xk_1_r_52;
  reg  [63:0] shifted_xk_1_r_53;
  reg  [63:0] shifted_xk_1_r_54;
  reg  [63:0] shifted_xk_1_r_55;
  reg  [63:0] shifted_xk_1_r_56;
  reg  [63:0] shifted_xk_1_r_57;
  reg  [63:0] shifted_xk_1_r_58;
  reg  [63:0] shifted_xk_1_r_59;
  reg  [63:0] shifted_xk_1_r_60;
  reg  [63:0] shifted_xk_1_r_61;
  reg  [63:0] shifted_xk_1_r_62;
  reg  [63:0] shifted_xk_1_r_63;
  reg  [63:0] shifted_xk_1_r_64;
  reg  [63:0] shifted_xk_1_r_65;
  reg  [63:0] shifted_xk_1_r_66;
  reg  [63:0] shifted_xk_1_r_67;
  reg  [63:0] shifted_xk_1_r_68;
  reg  [63:0] shifted_xk_1_r_69;
  reg  [63:0] shifted_xk_1_r_70;
  reg  [63:0] shifted_xk_1_r_71;
  reg  [63:0] shifted_xk_1_r_72;
  reg  [63:0] shifted_xk_1_r_73;
  reg  [63:0] shifted_xk_1_r_74;
  reg  [63:0] shifted_xk_1_r_75;
  reg  [63:0] shifted_xk_1_r_76;
  reg  [63:0] shifted_xk_1_r_77;
  reg  [63:0] shifted_xk_1_r_78;
  reg  [63:0] shifted_xk_1_r_79;
  reg  [63:0] shifted_xk_1_r_80;
  reg  [63:0] shifted_xk_1_r_81;
  reg  [63:0] shifted_xk_1_r_82;
  reg  [63:0] shifted_xk_1_r_83;
  reg  [63:0] shifted_xk_1_r_84;
  reg  [63:0] shifted_xk_1_r_85;
  reg  [63:0] shifted_xk_1_r_86;
  reg  [63:0] shifted_xk_1_r_87;
  reg  [63:0] shifted_xk_1_r_88;
  reg  [63:0] shifted_xk_1_r_89;
  reg  [63:0] shifted_xk_1_r_90;
  reg  [63:0] shifted_xk_1_r_91;
  reg  [63:0] shifted_xk_1_r_92;
  reg  [63:0] shifted_xk_1_r_93;
  reg  [63:0] shifted_xk_1_r_94;
  reg  [63:0] shifted_xk_1_r_95;
  reg  [63:0] shifted_xk_1_r_96;
  reg  [63:0] shifted_xk_1_r_97;
  reg  [63:0] shifted_xk_1_r_98;
  reg  [63:0] shifted_xk_1_r_99;
  reg  [63:0] shifted_xk_1_r_100;
  reg  [63:0] shifted_xk_1_r_101;
  reg  [63:0] shifted_xk_1_r_102;
  reg  [63:0] shifted_xk_1_r_103;
  reg  [63:0] shifted_xk_1_r_104;
  reg  [63:0] shifted_xk_1_r_105;
  reg  [63:0] shifted_xk_1_r_106;
  reg  [63:0] shifted_xk_1_r_107;
  reg  [63:0] shifted_xk_1_r_108;
  reg  [63:0] shifted_xk_1_r_109;
  reg  [63:0] shifted_xk_1_r_110;
  reg  [63:0] shifted_xk_1_r_111;
  reg  [63:0] shifted_xk_1_r_112;
  reg  [63:0] shifted_xk_1_r_113;
  reg  [63:0] shifted_xk_1_r_114;
  reg  [63:0] shifted_xk_1_r_115;
  reg  [63:0] shifted_xk_1_r_116;
  reg  [63:0] shifted_xk_1_r_117;
  reg  [63:0] shifted_xk_1_r_118;
  reg  [63:0] shifted_xk_1_r_119;
  reg  [63:0] shifted_xk_1_r_120;
  reg  [63:0] shifted_xk_1_r_121;
  reg  [63:0] shifted_xk_1_r_122;
  wire [63:0] _GEN = io_in_en ? io_xk_in_0 : 64'h0;
  wire [63:0] _GEN_0 = io_in_en ? io_xk_in_1 : 64'h0;
  wire        _GEN_1 = counter > 32'h31;
  wire        _GEN_2 = counter > 32'h40;
  wire        _GEN_3 = counter > 32'h7A;
  wire        _GEN_4 = counter > 32'h87;
  reg  [63:0] alpha_reg;
  reg  [31:0] tk_reg;
  always @(posedge clock) begin
    if (reset) begin
      counter <= 32'h0;
      x0_reg <= 64'h0;
      alpha_reg <= 64'h0;
      tk_reg <= 32'h0;
    end
    else begin
      if (io_counter_reset)
        counter <= 32'h0;
      else if (io_in_en)
        counter <= counter + 32'h1;
      if (counter == 32'h0)
        x0_reg <= io_xk_in_0;
      if (counter == 32'h7B)
        alpha_reg <= _alpha_gen_io_out_s;
      if (counter == 32'hC5)
        tk_reg <= _tk_gen_io_out_s;
    end
    shifted_x0_r <= x0_reg;
    shifted_x0_r_1 <= shifted_x0_r;
    shifted_x0_r_2 <= shifted_x0_r_1;
    shifted_x0_r_3 <= shifted_x0_r_2;
    shifted_x0_r_4 <= shifted_x0_r_3;
    shifted_x0_r_5 <= shifted_x0_r_4;
    shifted_x0_r_6 <= shifted_x0_r_5;
    shifted_x0_r_7 <= shifted_x0_r_6;
    shifted_x0_r_8 <= shifted_x0_r_7;
    shifted_x0_r_9 <= shifted_x0_r_8;
    shifted_x0_r_10 <= shifted_x0_r_9;
    shifted_x0_r_11 <= shifted_x0_r_10;
    shifted_x0_r_12 <= shifted_x0_r_11;
    shifted_x0_r_13 <= shifted_x0_r_12;
    shifted_x0_r_14 <= shifted_x0_r_13;
    shifted_x0_r_15 <= shifted_x0_r_14;
    shifted_x0_r_16 <= shifted_x0_r_15;
    shifted_x0_r_17 <= shifted_x0_r_16;
    shifted_x0_r_18 <= shifted_x0_r_17;
    shifted_x0_r_19 <= shifted_x0_r_18;
    shifted_x0_r_20 <= shifted_x0_r_19;
    shifted_x0_r_21 <= shifted_x0_r_20;
    shifted_x0_r_22 <= shifted_x0_r_21;
    shifted_x0_r_23 <= shifted_x0_r_22;
    shifted_x0_r_24 <= shifted_x0_r_23;
    shifted_x0_r_25 <= shifted_x0_r_24;
    shifted_x0_r_26 <= shifted_x0_r_25;
    shifted_x0_r_27 <= shifted_x0_r_26;
    shifted_x0_r_28 <= shifted_x0_r_27;
    shifted_x0_r_29 <= shifted_x0_r_28;
    shifted_x0_r_30 <= shifted_x0_r_29;
    shifted_x0_r_31 <= shifted_x0_r_30;
    shifted_x0_r_32 <= shifted_x0_r_31;
    shifted_x0_r_33 <= shifted_x0_r_32;
    shifted_x0_r_34 <= shifted_x0_r_33;
    shifted_x0_r_35 <= shifted_x0_r_34;
    shifted_x0_r_36 <= shifted_x0_r_35;
    shifted_x0_r_37 <= shifted_x0_r_36;
    shifted_x0_r_38 <= shifted_x0_r_37;
    shifted_x0_r_39 <= shifted_x0_r_38;
    shifted_x0_r_40 <= shifted_x0_r_39;
    shifted_x0_r_41 <= shifted_x0_r_40;
    shifted_x0_r_42 <= shifted_x0_r_41;
    shifted_x0_r_43 <= shifted_x0_r_42;
    shifted_x0_r_44 <= shifted_x0_r_43;
    shifted_x0_r_45 <= shifted_x0_r_44;
    shifted_x0_r_46 <= shifted_x0_r_45;
    shifted_x0_r_47 <= shifted_x0_r_46;
    shifted_x0_r_48 <= shifted_x0_r_47;
    shifted_x0_r_49 <= shifted_x0_r_48;
    shifted_x0_r_50 <= shifted_x0_r_49;
    shifted_x0_r_51 <= shifted_x0_r_50;
    shifted_x0_r_52 <= shifted_x0_r_51;
    shifted_x0_r_53 <= shifted_x0_r_52;
    shifted_x0_r_54 <= shifted_x0_r_53;
    shifted_x0_r_55 <= shifted_x0_r_54;
    shifted_x0_r_56 <= shifted_x0_r_55;
    shifted_x0_r_57 <= shifted_x0_r_56;
    shifted_x0_r_58 <= shifted_x0_r_57;
    shifted_x0_r_59 <= shifted_x0_r_58;
    shifted_x0_r_60 <= shifted_x0_r_59;
    shifted_x0_r_61 <= shifted_x0_r_60;
    shifted_x0_r_62 <= shifted_x0_r_61;
    shifted_x0 <= shifted_x0_r_62;
    shifted_xk_0_r <= io_xk_in_0;
    shifted_xk_0_r_1 <= shifted_xk_0_r;
    shifted_xk_0_r_2 <= shifted_xk_0_r_1;
    shifted_xk_0_r_3 <= shifted_xk_0_r_2;
    shifted_xk_0_r_4 <= shifted_xk_0_r_3;
    shifted_xk_0_r_5 <= shifted_xk_0_r_4;
    shifted_xk_0_r_6 <= shifted_xk_0_r_5;
    shifted_xk_0_r_7 <= shifted_xk_0_r_6;
    shifted_xk_0_r_8 <= shifted_xk_0_r_7;
    shifted_xk_0_r_9 <= shifted_xk_0_r_8;
    shifted_xk_0_r_10 <= shifted_xk_0_r_9;
    shifted_xk_0_r_11 <= shifted_xk_0_r_10;
    shifted_xk_0_r_12 <= shifted_xk_0_r_11;
    shifted_xk_0_r_13 <= shifted_xk_0_r_12;
    shifted_xk_0_r_14 <= shifted_xk_0_r_13;
    shifted_xk_0_r_15 <= shifted_xk_0_r_14;
    shifted_xk_0_r_16 <= shifted_xk_0_r_15;
    shifted_xk_0_r_17 <= shifted_xk_0_r_16;
    shifted_xk_0_r_18 <= shifted_xk_0_r_17;
    shifted_xk_0_r_19 <= shifted_xk_0_r_18;
    shifted_xk_0_r_20 <= shifted_xk_0_r_19;
    shifted_xk_0_r_21 <= shifted_xk_0_r_20;
    shifted_xk_0_r_22 <= shifted_xk_0_r_21;
    shifted_xk_0_r_23 <= shifted_xk_0_r_22;
    shifted_xk_0_r_24 <= shifted_xk_0_r_23;
    shifted_xk_0_r_25 <= shifted_xk_0_r_24;
    shifted_xk_0_r_26 <= shifted_xk_0_r_25;
    shifted_xk_0_r_27 <= shifted_xk_0_r_26;
    shifted_xk_0_r_28 <= shifted_xk_0_r_27;
    shifted_xk_0_r_29 <= shifted_xk_0_r_28;
    shifted_xk_0_r_30 <= shifted_xk_0_r_29;
    shifted_xk_0_r_31 <= shifted_xk_0_r_30;
    shifted_xk_0_r_32 <= shifted_xk_0_r_31;
    shifted_xk_0_r_33 <= shifted_xk_0_r_32;
    shifted_xk_0_r_34 <= shifted_xk_0_r_33;
    shifted_xk_0_r_35 <= shifted_xk_0_r_34;
    shifted_xk_0_r_36 <= shifted_xk_0_r_35;
    shifted_xk_0_r_37 <= shifted_xk_0_r_36;
    shifted_xk_0_r_38 <= shifted_xk_0_r_37;
    shifted_xk_0_r_39 <= shifted_xk_0_r_38;
    shifted_xk_0_r_40 <= shifted_xk_0_r_39;
    shifted_xk_0_r_41 <= shifted_xk_0_r_40;
    shifted_xk_0_r_42 <= shifted_xk_0_r_41;
    shifted_xk_0_r_43 <= shifted_xk_0_r_42;
    shifted_xk_0_r_44 <= shifted_xk_0_r_43;
    shifted_xk_0_r_45 <= shifted_xk_0_r_44;
    shifted_xk_0_r_46 <= shifted_xk_0_r_45;
    shifted_xk_0_r_47 <= shifted_xk_0_r_46;
    shifted_xk_0_r_48 <= shifted_xk_0_r_47;
    shifted_xk_0_r_49 <= shifted_xk_0_r_48;
    shifted_xk_0_r_50 <= shifted_xk_0_r_49;
    shifted_xk_0_r_51 <= shifted_xk_0_r_50;
    shifted_xk_0_r_52 <= shifted_xk_0_r_51;
    shifted_xk_0_r_53 <= shifted_xk_0_r_52;
    shifted_xk_0_r_54 <= shifted_xk_0_r_53;
    shifted_xk_0_r_55 <= shifted_xk_0_r_54;
    shifted_xk_0_r_56 <= shifted_xk_0_r_55;
    shifted_xk_0_r_57 <= shifted_xk_0_r_56;
    shifted_xk_0_r_58 <= shifted_xk_0_r_57;
    shifted_xk_0_r_59 <= shifted_xk_0_r_58;
    shifted_xk_0_r_60 <= shifted_xk_0_r_59;
    shifted_xk_0_r_61 <= shifted_xk_0_r_60;
    shifted_xk_0_r_62 <= shifted_xk_0_r_61;
    shifted_xk_0_r_63 <= shifted_xk_0_r_62;
    shifted_xk_0_r_64 <= shifted_xk_0_r_63;
    shifted_xk_0_r_65 <= shifted_xk_0_r_64;
    shifted_xk_0_r_66 <= shifted_xk_0_r_65;
    shifted_xk_0_r_67 <= shifted_xk_0_r_66;
    shifted_xk_0_r_68 <= shifted_xk_0_r_67;
    shifted_xk_0_r_69 <= shifted_xk_0_r_68;
    shifted_xk_0_r_70 <= shifted_xk_0_r_69;
    shifted_xk_0_r_71 <= shifted_xk_0_r_70;
    shifted_xk_0_r_72 <= shifted_xk_0_r_71;
    shifted_xk_0_r_73 <= shifted_xk_0_r_72;
    shifted_xk_0_r_74 <= shifted_xk_0_r_73;
    shifted_xk_0_r_75 <= shifted_xk_0_r_74;
    shifted_xk_0_r_76 <= shifted_xk_0_r_75;
    shifted_xk_0_r_77 <= shifted_xk_0_r_76;
    shifted_xk_0_r_78 <= shifted_xk_0_r_77;
    shifted_xk_0_r_79 <= shifted_xk_0_r_78;
    shifted_xk_0_r_80 <= shifted_xk_0_r_79;
    shifted_xk_0_r_81 <= shifted_xk_0_r_80;
    shifted_xk_0_r_82 <= shifted_xk_0_r_81;
    shifted_xk_0_r_83 <= shifted_xk_0_r_82;
    shifted_xk_0_r_84 <= shifted_xk_0_r_83;
    shifted_xk_0_r_85 <= shifted_xk_0_r_84;
    shifted_xk_0_r_86 <= shifted_xk_0_r_85;
    shifted_xk_0_r_87 <= shifted_xk_0_r_86;
    shifted_xk_0_r_88 <= shifted_xk_0_r_87;
    shifted_xk_0_r_89 <= shifted_xk_0_r_88;
    shifted_xk_0_r_90 <= shifted_xk_0_r_89;
    shifted_xk_0_r_91 <= shifted_xk_0_r_90;
    shifted_xk_0_r_92 <= shifted_xk_0_r_91;
    shifted_xk_0_r_93 <= shifted_xk_0_r_92;
    shifted_xk_0_r_94 <= shifted_xk_0_r_93;
    shifted_xk_0_r_95 <= shifted_xk_0_r_94;
    shifted_xk_0_r_96 <= shifted_xk_0_r_95;
    shifted_xk_0_r_97 <= shifted_xk_0_r_96;
    shifted_xk_0_r_98 <= shifted_xk_0_r_97;
    shifted_xk_0_r_99 <= shifted_xk_0_r_98;
    shifted_xk_0_r_100 <= shifted_xk_0_r_99;
    shifted_xk_0_r_101 <= shifted_xk_0_r_100;
    shifted_xk_0_r_102 <= shifted_xk_0_r_101;
    shifted_xk_0_r_103 <= shifted_xk_0_r_102;
    shifted_xk_0_r_104 <= shifted_xk_0_r_103;
    shifted_xk_0_r_105 <= shifted_xk_0_r_104;
    shifted_xk_0_r_106 <= shifted_xk_0_r_105;
    shifted_xk_0_r_107 <= shifted_xk_0_r_106;
    shifted_xk_0_r_108 <= shifted_xk_0_r_107;
    shifted_xk_0_r_109 <= shifted_xk_0_r_108;
    shifted_xk_0_r_110 <= shifted_xk_0_r_109;
    shifted_xk_0_r_111 <= shifted_xk_0_r_110;
    shifted_xk_0_r_112 <= shifted_xk_0_r_111;
    shifted_xk_0_r_113 <= shifted_xk_0_r_112;
    shifted_xk_0_r_114 <= shifted_xk_0_r_113;
    shifted_xk_0_r_115 <= shifted_xk_0_r_114;
    shifted_xk_0_r_116 <= shifted_xk_0_r_115;
    shifted_xk_0_r_117 <= shifted_xk_0_r_116;
    shifted_xk_0_r_118 <= shifted_xk_0_r_117;
    shifted_xk_0_r_119 <= shifted_xk_0_r_118;
    shifted_xk_0_r_120 <= shifted_xk_0_r_119;
    shifted_xk_0_r_121 <= shifted_xk_0_r_120;
    shifted_xk_0_r_122 <= shifted_xk_0_r_121;
    shifted_xk_1_r <= io_xk_in_1;
    shifted_xk_1_r_1 <= shifted_xk_1_r;
    shifted_xk_1_r_2 <= shifted_xk_1_r_1;
    shifted_xk_1_r_3 <= shifted_xk_1_r_2;
    shifted_xk_1_r_4 <= shifted_xk_1_r_3;
    shifted_xk_1_r_5 <= shifted_xk_1_r_4;
    shifted_xk_1_r_6 <= shifted_xk_1_r_5;
    shifted_xk_1_r_7 <= shifted_xk_1_r_6;
    shifted_xk_1_r_8 <= shifted_xk_1_r_7;
    shifted_xk_1_r_9 <= shifted_xk_1_r_8;
    shifted_xk_1_r_10 <= shifted_xk_1_r_9;
    shifted_xk_1_r_11 <= shifted_xk_1_r_10;
    shifted_xk_1_r_12 <= shifted_xk_1_r_11;
    shifted_xk_1_r_13 <= shifted_xk_1_r_12;
    shifted_xk_1_r_14 <= shifted_xk_1_r_13;
    shifted_xk_1_r_15 <= shifted_xk_1_r_14;
    shifted_xk_1_r_16 <= shifted_xk_1_r_15;
    shifted_xk_1_r_17 <= shifted_xk_1_r_16;
    shifted_xk_1_r_18 <= shifted_xk_1_r_17;
    shifted_xk_1_r_19 <= shifted_xk_1_r_18;
    shifted_xk_1_r_20 <= shifted_xk_1_r_19;
    shifted_xk_1_r_21 <= shifted_xk_1_r_20;
    shifted_xk_1_r_22 <= shifted_xk_1_r_21;
    shifted_xk_1_r_23 <= shifted_xk_1_r_22;
    shifted_xk_1_r_24 <= shifted_xk_1_r_23;
    shifted_xk_1_r_25 <= shifted_xk_1_r_24;
    shifted_xk_1_r_26 <= shifted_xk_1_r_25;
    shifted_xk_1_r_27 <= shifted_xk_1_r_26;
    shifted_xk_1_r_28 <= shifted_xk_1_r_27;
    shifted_xk_1_r_29 <= shifted_xk_1_r_28;
    shifted_xk_1_r_30 <= shifted_xk_1_r_29;
    shifted_xk_1_r_31 <= shifted_xk_1_r_30;
    shifted_xk_1_r_32 <= shifted_xk_1_r_31;
    shifted_xk_1_r_33 <= shifted_xk_1_r_32;
    shifted_xk_1_r_34 <= shifted_xk_1_r_33;
    shifted_xk_1_r_35 <= shifted_xk_1_r_34;
    shifted_xk_1_r_36 <= shifted_xk_1_r_35;
    shifted_xk_1_r_37 <= shifted_xk_1_r_36;
    shifted_xk_1_r_38 <= shifted_xk_1_r_37;
    shifted_xk_1_r_39 <= shifted_xk_1_r_38;
    shifted_xk_1_r_40 <= shifted_xk_1_r_39;
    shifted_xk_1_r_41 <= shifted_xk_1_r_40;
    shifted_xk_1_r_42 <= shifted_xk_1_r_41;
    shifted_xk_1_r_43 <= shifted_xk_1_r_42;
    shifted_xk_1_r_44 <= shifted_xk_1_r_43;
    shifted_xk_1_r_45 <= shifted_xk_1_r_44;
    shifted_xk_1_r_46 <= shifted_xk_1_r_45;
    shifted_xk_1_r_47 <= shifted_xk_1_r_46;
    shifted_xk_1_r_48 <= shifted_xk_1_r_47;
    shifted_xk_1_r_49 <= shifted_xk_1_r_48;
    shifted_xk_1_r_50 <= shifted_xk_1_r_49;
    shifted_xk_1_r_51 <= shifted_xk_1_r_50;
    shifted_xk_1_r_52 <= shifted_xk_1_r_51;
    shifted_xk_1_r_53 <= shifted_xk_1_r_52;
    shifted_xk_1_r_54 <= shifted_xk_1_r_53;
    shifted_xk_1_r_55 <= shifted_xk_1_r_54;
    shifted_xk_1_r_56 <= shifted_xk_1_r_55;
    shifted_xk_1_r_57 <= shifted_xk_1_r_56;
    shifted_xk_1_r_58 <= shifted_xk_1_r_57;
    shifted_xk_1_r_59 <= shifted_xk_1_r_58;
    shifted_xk_1_r_60 <= shifted_xk_1_r_59;
    shifted_xk_1_r_61 <= shifted_xk_1_r_60;
    shifted_xk_1_r_62 <= shifted_xk_1_r_61;
    shifted_xk_1_r_63 <= shifted_xk_1_r_62;
    shifted_xk_1_r_64 <= shifted_xk_1_r_63;
    shifted_xk_1_r_65 <= shifted_xk_1_r_64;
    shifted_xk_1_r_66 <= shifted_xk_1_r_65;
    shifted_xk_1_r_67 <= shifted_xk_1_r_66;
    shifted_xk_1_r_68 <= shifted_xk_1_r_67;
    shifted_xk_1_r_69 <= shifted_xk_1_r_68;
    shifted_xk_1_r_70 <= shifted_xk_1_r_69;
    shifted_xk_1_r_71 <= shifted_xk_1_r_70;
    shifted_xk_1_r_72 <= shifted_xk_1_r_71;
    shifted_xk_1_r_73 <= shifted_xk_1_r_72;
    shifted_xk_1_r_74 <= shifted_xk_1_r_73;
    shifted_xk_1_r_75 <= shifted_xk_1_r_74;
    shifted_xk_1_r_76 <= shifted_xk_1_r_75;
    shifted_xk_1_r_77 <= shifted_xk_1_r_76;
    shifted_xk_1_r_78 <= shifted_xk_1_r_77;
    shifted_xk_1_r_79 <= shifted_xk_1_r_78;
    shifted_xk_1_r_80 <= shifted_xk_1_r_79;
    shifted_xk_1_r_81 <= shifted_xk_1_r_80;
    shifted_xk_1_r_82 <= shifted_xk_1_r_81;
    shifted_xk_1_r_83 <= shifted_xk_1_r_82;
    shifted_xk_1_r_84 <= shifted_xk_1_r_83;
    shifted_xk_1_r_85 <= shifted_xk_1_r_84;
    shifted_xk_1_r_86 <= shifted_xk_1_r_85;
    shifted_xk_1_r_87 <= shifted_xk_1_r_86;
    shifted_xk_1_r_88 <= shifted_xk_1_r_87;
    shifted_xk_1_r_89 <= shifted_xk_1_r_88;
    shifted_xk_1_r_90 <= shifted_xk_1_r_89;
    shifted_xk_1_r_91 <= shifted_xk_1_r_90;
    shifted_xk_1_r_92 <= shifted_xk_1_r_91;
    shifted_xk_1_r_93 <= shifted_xk_1_r_92;
    shifted_xk_1_r_94 <= shifted_xk_1_r_93;
    shifted_xk_1_r_95 <= shifted_xk_1_r_94;
    shifted_xk_1_r_96 <= shifted_xk_1_r_95;
    shifted_xk_1_r_97 <= shifted_xk_1_r_96;
    shifted_xk_1_r_98 <= shifted_xk_1_r_97;
    shifted_xk_1_r_99 <= shifted_xk_1_r_98;
    shifted_xk_1_r_100 <= shifted_xk_1_r_99;
    shifted_xk_1_r_101 <= shifted_xk_1_r_100;
    shifted_xk_1_r_102 <= shifted_xk_1_r_101;
    shifted_xk_1_r_103 <= shifted_xk_1_r_102;
    shifted_xk_1_r_104 <= shifted_xk_1_r_103;
    shifted_xk_1_r_105 <= shifted_xk_1_r_104;
    shifted_xk_1_r_106 <= shifted_xk_1_r_105;
    shifted_xk_1_r_107 <= shifted_xk_1_r_106;
    shifted_xk_1_r_108 <= shifted_xk_1_r_107;
    shifted_xk_1_r_109 <= shifted_xk_1_r_108;
    shifted_xk_1_r_110 <= shifted_xk_1_r_109;
    shifted_xk_1_r_111 <= shifted_xk_1_r_110;
    shifted_xk_1_r_112 <= shifted_xk_1_r_111;
    shifted_xk_1_r_113 <= shifted_xk_1_r_112;
    shifted_xk_1_r_114 <= shifted_xk_1_r_113;
    shifted_xk_1_r_115 <= shifted_xk_1_r_114;
    shifted_xk_1_r_116 <= shifted_xk_1_r_115;
    shifted_xk_1_r_117 <= shifted_xk_1_r_116;
    shifted_xk_1_r_118 <= shifted_xk_1_r_117;
    shifted_xk_1_r_119 <= shifted_xk_1_r_118;
    shifted_xk_1_r_120 <= shifted_xk_1_r_119;
    shifted_xk_1_r_121 <= shifted_xk_1_r_120;
    shifted_xk_1_r_122 <= shifted_xk_1_r_121;
  end // always @(posedge)
  cmplx_dot_iterative eu_norm_dot (
    .clock            (clock),
    .reset            (reset),
    .io_vec_a_0       (_GEN),
    .io_vec_a_1       (_GEN_0),
    .io_vec_b_0       (_GEN),
    .io_vec_b_1       (_GEN_0),
    .io_counter_reset (io_in_en & io_counter_reset),
    .io_in_en         (io_in_en),
    .io_out_real      (_eu_norm_dot_io_out_real)
  );
  alpha alpha_gen (
    .clock            (clock),
    .reset            (reset),
    .io_in_x0         (_GEN_2 ? shifted_x0 : 64'h0),
    .io_in_eu_norm    (_GEN_2 ? _sqrt_io_out_s : 32'h0),
    .io_in_en         (_GEN_2),
    .io_counter_reset (_GEN_2 & io_counter_reset),
    .io_out_s         (_alpha_gen_io_out_s)
  );
  vk_gen vk_gen (
    .clock            (clock),
    .reset            (reset),
    .io_xk_in_0       (_GEN_3 ? shifted_xk_0_r_122 : 64'h0),
    .io_xk_in_1       (_GEN_3 ? shifted_xk_1_r_122 : 64'h0),
    .io_alpha_in      (_GEN_3 ? _alpha_gen_io_out_s : 64'h0),
    .io_in_en         (_GEN_3),
    .io_counter_reset (_GEN_3 & io_counter_reset),
    .io_out_s_0       (_vk_gen_io_out_s_0),
    .io_out_s_1       (_vk_gen_io_out_s_1)
  );
  tk_gen tk_gen (
    .clock            (clock),
    .reset            (reset),
    .io_vk_in_0       (_GEN_4 ? _vk_gen_io_out_s_0 : 64'h0),
    .io_vk_in_1       (_GEN_4 ? _vk_gen_io_out_s_1 : 64'h0),
    .io_in_en         (_GEN_4),
    .io_counter_reset (_GEN_4 & io_counter_reset),
    .io_out_s         (_tk_gen_io_out_s)
  );
  FP_sqrt_32_15 sqrt (
    .clock    (clock),
    .reset    (reset),
    .io_in_en (io_in_en & _GEN_1),
    .io_in_a  (io_in_en & _GEN_1 ? _eu_norm_dot_io_out_real : 32'h0),
    .io_out_s (_sqrt_io_out_s)
  );
  assign io_alpha_out = alpha_reg;
  assign io_out_tk = tk_reg;
  assign io_out_valid = counter == 32'hC6;
endmodule

